'use strict';
const assert=require('node:assert/strict');
const X=require('../scripts/field-event.js'),UI=require('../scripts/experience-ui.js');
const results=[];const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}};
function quiet(){const r=new X.Run(42,'bow','standard');r.spawnTimer=r.eliteAt=r.bossAt=1e8;r.autoItem=false;r.cool.attack=1e8;return r;}
function target(r){const e=r.spawn(0,false,r.p.x+150,r.p.y);e.born=0;e.hp=e.max=10000;e.speed=0;e.cd=1e8;return e;}
function choose(r,id){r.openChoice('upgrade');r.choices=[id];assert(r.choose(0));}
test('expensive unprioritized skill does not immediately block affordable output',()=>{const r=quiet(),e=target(r);r.skills={rain:1,angler:1};r.p.mp=24;r.updateSkills(.05,e);assert.equal(r.skillCasts?.rain,1);assert.equal(r.p.mp,2);});
test('expensive skill reserves after bounded waiting and eventually casts',()=>{const r=quiet(),e=target(r);r.skills={rain:1,angler:1};r.p.mp=24;r.updateSkills(.05,e);r.t=1.1;r.p.mp=24;r.cool.rain=0;r.updateSkills(.05,e);assert.equal(r.skillBudget,'angler');assert.equal(r.p.mp,24);r.p.mp=26;r.updateSkills(.05,e);assert.equal(r.skillCasts.angler,1);});
test('first learned damage skill becomes primary; subsequent skills and explicit balanced mode do not override it',()=>{const r=quiet();choose(r,'armor');assert(!r.primarySkill);choose(r,'rain');assert.equal(r.primarySkill,'rain');choose(r,'angler');assert.equal(r.primarySkill,'rain');r.setPrimary(null);choose(r,'flame');assert.equal(r.primarySkill,null);});
test('urgent survival still precedes primary, manual skills stay excluded',()=>{const r=quiet(),e=target(r);r.skills={rain:1,armor:1};r.setPrimary('rain');r.p.hp=20;r.p.mp=20;r.updateSkills(.05,e);assert.equal(r.skillCasts.armor,1);r.setManual('rain');assert(!r.skillOrder(e).includes('rain'));});
test('choice history separates missing opportunity from survival deferral',()=>{const r=quiet();r.skills={rain:1};r.level=2;r.openChoice();r.choices=['spring','vigor','flame'];assert(r.choose(1));r.openChoice();r.choices=['flame','armor','power'];assert(r.choose(2));const p=r.loopSummary().routes.lushui;assert.equal(p.trainingDeferrals,1);assert.equal(p.offersWithoutTarget,1);});
test('loop records are frozen in result and reset on a new run',()=>{const r=quiet();choose(r,'rain');target(r);r.step(.05);r.end('主动结束');const before=JSON.stringify(r.result.loop);r.loopLog().decisions.push({at:999});assert.equal(JSON.stringify(r.result.loop),before);assert.equal(quiet().loopSummary().decisions.length,0);});
test('standard finale starts at 11:15; endless does not',()=>{for(const mode of ['standard','endless']){const r=quiet();r.mode=mode;r.t=674.94;r.step(.05);assert(!r.finalStarted);r.step(.05);assert.equal(r.finalStarted,mode==='standard');}});
test('presentation describes automatic mana use and meaningful primary without hidden randomness',()=>{const r=quiet();choose(r,'rain');const html=UI.card(r,'angler',0,()=>'',{},{});assert.match(html,/自动施放/);assert.match(html,/共用法力/);assert.match(UI.loopPanel(r),/清夕雨/);assert(!html.includes('undefined'));});
test('new loop summary survives archive roundtrip; legacy records remain valid',()=>{const fs=require('fs'),vm=require('vm');let saved='';const w={XJ:X,localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},Date,Math};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),w);const r=quiet();choose(r,'rain');r.end('主动结束');w.XJArchive.record(r);const a=JSON.parse(saved);assert(a.records[0].loop);assert.equal(a.records[0].loop.decisions,undefined);w.XJArchive.merge({schema:1,records:[{id:'legacy',item:'bow',time:50,kills:3}],marks:[],best:{}});assert(w.XJArchive.data.records.some(x=>x.id==='legacy'));});
console.log(JSON.stringify({suite:'core loop',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
