'use strict';
// Constructed contract/regression scenarios; not natural-play or browser E2E evidence.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const X=require('../scripts/field-event.js'),results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
const paths=Object.fromEntries(X.Cultivation.routes.map(r=>[r.id,[...r.ids]]));
function choose(r,id,kind='upgrade'){r.openChoice(kind);r.choices=[id];return r.choose(0);}
function start(id='gate',seed=1){const r=new X.Run(seed,'bow','standard');r.opening();assert(r.choose(r.choices.indexOf(id)));return r;}
function enemy(r,dx=70){const e=r.spawn(0,false,r.p.x+dx,r.p.y);e.born=0;e.hp=e.max=10000;e.stun=0;return e;}
test('browser and CommonJS entry points load cultivation in dependency order',()=>{const html=fs.readFileSync(require.resolve('../index.html'),'utf8');const names=['medicine.js','cultivation.js','field-event.js','experience-ui.js','game.js'];for(let i=1;i<names.length;i++)assert(html.indexOf(names[i-1])<html.indexOf(names[i]));assert.equal(X.Cultivation.version,'0.31.0');});
test('opening exposes exactly twenty foundations in four paths; selection fixes five slots',()=>{for(const [dao,ids] of Object.entries(paths))for(const id of ids){const r=new X.Run(1,'bow');assert.equal(r.realm,'筑基');assert.equal(r.skillLimit,5);r.opening();assert.deepEqual(new Set(r.choices),new Set(Object.values(paths).flat()));assert.equal(r.choices.length,20);assert(r.choose(r.choices.indexOf(id)));assert.equal(r.dao,dao);assert.equal(r.lv(id),1);assert.equal(r.realm,'筑基');assert.deepEqual(r.pathSkills().map(s=>s.id),ids);const other=dao==='mingyang'?'rain':'gate';assert.equal(choose(r,other,'event'),false);for(const own of ids.filter(x=>x!==id))assert(choose(r,own));assert.equal(Object.keys(r.skills).length,5);}});
test('five breakthroughs honor both sides of every level threshold and realm milestone',()=>{for(const ids of Object.values(paths)){const r=start(ids[0]);for(const id of ids){while(r.lv(id)<2)assert(choose(r,id));}for(const [i,need] of [7,11,15,20,24].entries()){const id=ids[i];r.level=need-1;assert(!r.valid().includes(id));assert.equal(choose(r,id,'event'),false);assert.equal(r.lv(id),2);r.level=need;assert(r.valid().includes(id));assert(choose(r,id));assert.equal(r.masteredCount(),i+1);assert.equal(r.realm,['紫府','紫府','紫府中期','大真人','五法圆满'][i]);}assert.deepEqual(r.realmHistory.map(x=>x.realm),['紫府','紫府中期','大真人','五法圆满']);assert.deepEqual(r.fruits,{});assert.equal(r.fruitAt,null);assert.equal(r.recipe(),false);}});
test('gate foundations suppress nearby foes for short duration without allies; mastery summons six',()=>{for(const rank of [1,2,3]){const r=start();r.skills.gate=rank;r.cool.gate=0;const e=enemy(r);r.updateSkills(0,e);assert.equal(r.p.mp,100-(rank<3?8:26));assert.equal(r.cool.gate,9);assert.equal(r.allies.count,rank<3?0:6);if(rank<3){assert(Math.abs(e.stun-(.4+rank*.2))<1e-9);assert.equal(r.fx.list().find(f=>f.kind==='foundationGate').r,55+rank*20);}}});
test('manual selection rejects foundations and accepts supported third-rank powers',()=>{for(const id of Object.values(paths).flat()){const r=start(id);for(const rank of [1,2]){r.skills[id]=rank;assert.equal(r.setManual(id),false,id);assert.equal(r.manualSkill,null);assert.equal(r.canPrimary(id),false);}r.skills[id]=3;if(!r.isPassive(id))assert.equal(r.setManual(id),true,id);assert(r.setManual(null));}});
test('first foundation is guaranteed whenever cultivable, including rerolls and event offers',()=>{for(let seed=1;seed<=100;seed++)for(const id of Object.values(paths).flat()){const r=start(id,seed);r.level=7;for(const own of r.pathSkills().map(s=>s.id))if(own!==id)assert(choose(r,own));for(const rank of [1,2]){r.skills[id]=rank;for(const kind of ['upgrade','event']){r.openChoice(kind,'庚金');assert(r.choices.includes(id));r.rerolls=1;assert(r.reroll());assert(r.choices.includes(id));assert.equal(new Set(r.choices).size,3);}}r.level=6;r.skills[id]=2;r.openChoice();assert(!r.choices.includes(id));}});
test('new runs add no fruit recipes or gift; historical fruit records survive archive roundtrip',()=>{assert.deepEqual(X.RECIPES,[]);let saved='';const w={XJ:X,localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},Date,Math};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),w);w.XJArchive.merge({schema:1,records:[{id:'legacy',item:'bow',time:100,kills:20,fruits:{mingyang:true},skills:{gate:3,body:2,edict:1,dusk:1,light:1}}],marks:['fruit:mingyang'],best:{}});const r=start('rain');r.openChoice('gift');assert(!r.choices.includes('firegift'));r.state='running';r.end('主动结束');w.XJArchive.record(r);const data=JSON.parse(saved),old=data.records.find(x=>x.id==='legacy'),latest=data.records.at(-1);assert.equal(old.fruits.mingyang,true);assert.equal(Object.keys(old.skills).length,5);assert(data.marks.includes('fruit:mingyang'));assert.equal(latest.realm,'筑基');assert.equal(latest.dao,'lushui');assert.deepEqual(latest.fruits,{});assert(!w.XJArchive.nextGoal().includes('果位'));});
test('archive next goals exclude closed content while retaining old milestones',()=>{const w={XJ:X,localStorage:{getItem:()=>null,setItem:()=>{}},Date,Math};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),w);w.XJArchive.merge({schema:1,records:[],marks:['firstWin',...X.ITEMS.filter(i=>i.id!=='screen').map(i=>'win:'+i.id)],best:{}});assert(!w.XJArchive.nextGoal().includes('重明洞玄屏'));w.XJArchive.merge({schema:1,records:[],marks:['win:screen','fruit:mingyang',...X.Cultivation.routes.flatMap(r=>r.ids.map(id=>'master:'+id))],best:{}});assert.match(w.XJArchive.nextGoal(),/诸法已历/);assert(w.XJArchive.data.marks.includes('win:screen'));assert(w.XJArchive.data.marks.includes('fruit:mingyang'));});
console.log(JSON.stringify({suite:'cultivation contracts (constructed)',passed:results.filter(x=>x.pass).length,total:results.length,results},null,2));process.exitCode=results.every(x=>x.pass)?0:1;
