const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),X=require('../scripts/field-event.js');
const rows=[];function test(name,fn){try{fn();rows.push({name,pass:true})}catch(e){rows.push({name,pass:false,error:e.stack})}}
function run(dao='mingyang',n=0){const r=new X.Run(42,'dasheng','standard');r.dao=dao;r.skills=Object.fromEntries(X.Cultivation.routes.find(x=>x.id===dao).ids.map((id,i)=>[id,i<n?3:1]));r.level=24;r.updateRealm();r.autoItem=false;r.cool.attack=999;r.spawnTimer=r.eliteAt=r.bossAt=99999;return r;}
function enemy(r,x,y=0){const e=r.spawn(0,false,r.p.x+x,r.p.y+y);e.born=0;e.hp=e.max=10000;return e;}
test('entry, identity, training and five-weapon catalog are wired',()=>{const html=fs.readFileSync('index.html','utf8');assert(html.indexOf('dasheng.js')>html.indexOf('cultivation.js'));assert(html.indexOf('dasheng.js')<html.indexOf('field-event.js'));const r=run();assert.equal(r.itemDef.name,'大昇长戟');assert.equal(X.ITEMS.filter(i=>i.id!=='screen').length,5);const UI=require('../scripts/experience-ui.js');assert(UI.trainingInfo(r,'weapon').stat(2).includes('190'));});
test('auto sweep strikes front and flank but not rear, costs no MP',()=>{const r=run();const a=enemy(r,120),b=enemy(r,100,100),c=enemy(r,-100);r.autoAttack(a);assert.equal(a.hp,9966);assert.equal(b.hp,9966);assert.equal(c.hp,10000);assert.equal(r.p.mp,100);assert.equal(r.telemetry.autoShots,1);});
test('foundation and lushui never manifest mingyang lights; cost and cooldown reject invalid casts',()=>{for(const r of [run(),run('lushui',5)]){enemy(r,120);assert(r.itemUse());assert.equal(r.p.mp,76);assert.equal(r.cool.item,7);assert(!r.itemUse());assert(!r.dashengLights?.length);}const r=run();assert(!r.itemUse());assert.equal(r.p.mp,100);enemy(r,120);r.p.mp=23;assert(!r.itemUse());assert.equal(r.p.mp,23);});
test('manifested lights scale with same-dao powers; miss persists and pause freezes',()=>{for(const n of [1,3,4,5]){const r=run('mingyang',n);const e=enemy(r,80);assert(r.itemUse());assert.equal(r.dashengLights.length,n);r.enemies.remove(e);r.updateZones(.05);assert.equal(r.dashengLights.length,n);const life=r.dashengLights[0].life;r.state='paused';r.updateZones(.05);assert.equal(r.dashengLights[0].life,life);r.state='running';for(let i=0;i<81;i++)r.updateZones(.05);assert.equal(r.dashengLights.length,0);}});
test('each light hits once and is consumed, no repeated hidden damage',()=>{const r=run('mingyang',1);let e=enemy(r,80);r.itemUse();r.enemies.remove(e);r.updateZones(0);const l=r.dashengLights[0];e=enemy(r,l.x-r.p.x,l.y-r.p.y);r.updateZones(0);assert.equal(e.hp,9976);assert.equal(r.dashengLights.length,0);r.updateZones(.05);assert.equal(e.hp,9976);});
test('spring charges consumed once per sweep; old and new weapon histories preserved',()=>{const r=run('lushui',1);const a=enemy(r,100),b=enemy(r,100,40);r.cool.springPower=8;r.springCharges=6;r.autoAttack(a);assert.equal(r.springCharges,5);assert.equal(a.hp,9932);assert.equal(b.hp,9932);let saved='';const w={XJ:X,localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},Date,Math};w.window=w;vm.runInNewContext(fs.readFileSync('scripts/archive.js','utf8'),w);w.XJArchive.merge({schema:1,records:[{id:'legacy',item:'screen',time:10,kills:0}],marks:['win:screen'],best:{}});r.end('主动结束');w.XJArchive.record(r);const d=JSON.parse(saved);assert(d.records.some(x=>x.item==='screen'));assert(d.records.some(x=>x.item==='dasheng'));});
console.log(JSON.stringify({passed:rows.filter(x=>x.pass).length,total:rows.length,rows},null,2));process.exitCode=rows.every(x=>x.pass)?0:1;
