'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const X=require('../scripts/field-event.js'),{Run,FieldEvent,dist}=X,results=[];
const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}};
function quiet(){const r=new Run(42,'sword','standard');r.spawnTimer=r.eliteAt=r.bossAt=1e8;r.autoItem=false;r.cool.attack=1e8;return r;}
function event(kind){const r=quiet(),s=FieldEvent.schedule.find(s=>s.kind===kind);r.t=s.at;r.updateFieldEvent();return r;}
function enter(r){r.p.x=r.fieldEvent.x;r.p.y=r.fieldEvent.y;r.updateFieldEvent();}
function tick(r,seconds){for(let i=0;i<Math.round(seconds/.05);i++){r.t+=.05;r.updateFieldEvent(.05);}}
function kill(r){for(const e of r.enemies.list().filter(e=>e.fieldGuard&&e.fieldEventId===r.fieldEvent.id)){e.born=0;r.hit(e,1e6);}}
test('自然时钟先行囊后试阵，同一时间只有一个事件',()=>{const r=quiet();while(r.t<50.05)r.step(.05);assert.equal(r.fieldEvent.kind,'cache');while(r.t<90.05)r.step(.05);assert.equal(r.fieldEvent.kind,'trial');assert.equal(r.fieldHistory.length,1);assert.equal(r.fieldHistory[0].status,'expired');});
test('未触发场景选址不改变战斗随机序列',()=>{const a=quiet(),b=quiet();a.t=50;a.updateFieldEvent();assert.equal(a.random(),b.random());});
test('拾取离圈清零；连续两秒奖励并只发一次',()=>{const r=event('cache');assert(!r.completeFieldEvent());enter(r);tick(r,1);r.p.x+=100;tick(r,.1);assert.equal(r.fieldEvent.progress,0);enter(r);tick(r,2);assert.equal(r.fieldEvent.status,'completed');assert.equal(r.pending.length,1);r.updateFieldEvent();assert(!r.completeFieldEvent());assert.equal(r.pending.length,1);r.nextChoice();assert.equal(r.choiceKind,'event');assert.equal(r.choiceSource,'cache');assert(r.choose(0));assert.equal(r.log.at(-1).type,'event');});
test('据守离圈保留进度，增援有限，完成选择加重抽',()=>{const r=event('hold');enter(r);tick(r,4);assert(r.enemies.count>0);const before=r.fieldEvent.progress;r.p.x+=250;tick(r,1);assert.equal(r.fieldEvent.progress,before);enter(r);tick(r,6.05);assert.equal(r.fieldEvent.status,'completed');assert.equal(r.pending.length,1);assert.equal(r.rerolls,1);assert(r.enemies.count<=8);});
test('暂停及选卡冻结时钟、进度、敌人增援',()=>{for(const kind of ['cache','hold','chase']){const r=event(kind);enter(r);for(const state of ['paused','choice']){r.state=state;const before=JSON.stringify([r.t,r.fieldEvent,r.enemies.count]);r.step(.05);r.updateFieldEvent(.05);assert.equal(JSON.stringify([r.t,r.fieldEvent,r.enemies.count]),before);}}});
test('携物敌修远离玩家，迟缓、定身、诱引仍有效',()=>{const r=event('chase');enter(r);const e=r.enemies.list()[0];e.born=0;let d=dist(e,r.p);r.updateEnemies(.1);assert(dist(e,r.p)>d);let x=e.x;e.root=1;r.updateEnemies(.1);assert.equal(e.x,x);e.root=0;e.slow=1;r.updateEnemies(.1);assert(e.x-x<5);e.lured=1;e.lureX=e.x-100;e.lureY=e.y;x=e.x;r.updateEnemies(.1);assert(e.x<x);});
test('追击真实击杀发一次参悟和八额外经验；直接移除不发',()=>{const r=event('chase');enter(r);const e=r.enemies.list()[0];r.enemies.remove(e);r.updateFieldEvent();assert.equal(r.pending.length,0);const a=event('chase');enter(a);kill(a);assert.equal(a.fieldEvent.status,'completed');assert.equal(a.pending.length,1);assert.equal(a.xp,8);kill(a);assert.equal(a.pending.length,1);});
test('敌人池满不生成半组守卫，空位恢复后可触发',()=>{for(const kind of ['trial','chase']){const r=event(kind);while(r.enemies.count<r.enemies.max)r.spawn(0,false,100,100);enter(r);assert.equal(r.fieldEvent.status,'available');r.enemies.forEach(e=>r.enemies.remove(e));r.updateFieldEvent();assert.equal(r.fieldEvent.status,'active');assert.equal(r.enemies.count,kind==='trial'?3:1);}});
test('上一事件守卫不能完成当前试阵',()=>{const r=event('chase');enter(r);const old=r.enemies.list()[0];r.abandonFieldEvent();r.t=90;r.updateFieldEvent();enter(r);old.born=0;r.hit(old,1e6);assert.equal(r.fieldEvent.kills,0);kill(r);assert.equal(r.rerolls,1);});
test('到期边界或放弃不发迟到奖励，不额外扣资源',()=>{for(const kind of ['trial','cache','hold','chase'])for(const abandon of [false,true]){const r=event(kind);enter(r);r.rerolls=2;const mp=r.p.mp;if(abandon)r.abandonFieldEvent();else{r.t=r.fieldEvent.deadline;r.updateFieldEvent();}kill(r);assert.equal(r.pending.length,0);assert.equal(r.rerolls,2);assert.equal(r.p.mp,mp);assert.equal(r.fieldEvent.status,abandon?'abandoned':'expired');}});
test('死亡后不能补发机缘奖励',()=>{const r=event('hold');enter(r);r.p.hp=1;r.hurt(100);assert.equal(r.state,'ended');r.updateFieldEvent(10);assert.equal(r.pending.length,0);assert(!r.completeFieldEvent());});
test('十二分钟四次额外选择预算，无旧定时参悟叠加',()=>{const r=quiet();for(const slot of FieldEvent.schedule){r.t=slot.at;r.updateFieldEvent();enter(r);if(['trial','chase'].includes(slot.kind))kill(r);else tick(r,slot.kind==='cache'?2:10.05);while(r.pending.length||r.state==='choice'){if(r.state==='running')r.nextChoice();if(r.state==='choice')r.choose(0);}}assert.equal(r.fieldRewards,4);assert.equal(r.log.filter(l=>l.type==='event').length,4);assert.equal(r.rerolls,2);r.t=680;r.step(.05);assert.equal(r.pending.length,0);assert.notEqual(r.state,'choice');});
test('事件选卡复用缺项保底、重抽以及有效候选',()=>{const r=event('cache');r.skills={gate:1};r.offerMisses={mingyang:3};enter(r);tick(r,2);r.nextChoice();assert(r.choices.some(id=>X.RECIPES[0].ids.includes(id)&&!r.lv(id)));r.rerolls=1;assert(r.reroll());assert.equal(r.rerolls,0);assert.equal(new Set(r.choices).size,3);});
test('结算包含多次机缘历史，旧快照不会被续战修改',()=>{const r=event('cache');enter(r);tick(r,2);r.nextChoice();r.choose(0);r.t=90;r.updateFieldEvent();r.abandonFieldEvent();r.end('破阵功成');assert.equal(r.result.fieldHistory.length,2);const result=r.result,old=JSON.stringify(result);assert(r.continueEndless());r.t=780;r.updateFieldEvent();assert(FieldEvent.live(r.fieldEvent));assert.equal(JSON.stringify(result),old);});
test('无尽同一时段不重复刷事件；终阵关闭未完成机缘',()=>{const r=event('hold');r.finalStarted=true;r.updateFieldEvent();assert.equal(r.fieldEvent.status,'expired');r.t=780;r.mode='endless';r.updateFieldEvent();const id=r.fieldEvent.id;r.abandonFieldEvent();r.updateFieldEvent();assert.equal(r.fieldEvent.id,id);assert.equal(r.fieldEvent.status,'abandoned');r.t=965;r.updateFieldEvent();assert.notEqual(r.fieldEvent.id,id);});
test('胜利续战保留技能、箓气、寿元与资源，死亡不能续战',()=>{const r=quiet();r.skills={gate:3};r.gift='life';r.life=4;r.p.hp=43;r.p.mp=25;r.t=725;r.end('破阵功成');assert(r.continueEndless());assert.equal(r.mode,'endless');assert.equal(r.lv('gate'),3);assert.equal(r.life,4);assert.equal(r.p.hp,43);assert.equal(r.p.mp,25);assert.equal(r.bossAt,905);r.end('身死道消');assert(!r.continueEndless());});
test('档案兼容旧事件并保留新机缘列表，清洗未知字段',()=>{let saved='';const context={XJ:X,localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},Date,Math};context.window=context;vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),context);const old={schema:1,records:[{id:'old',item:'sword',time:90,kills:1,fieldEvent:{site:'pine',status:'completed',kills:3}}],marks:[],best:{}};context.XJArchive.merge(old);const r=event('cache');enter(r);tick(r,2);r.end();context.XJArchive.record(r);const records=JSON.parse(saved).records;assert.equal(records[0].fieldEvent.kills,3);assert.equal(records[1].fieldHistory[0].kind,'cache');assert.equal(records[1].fieldHistory[0].status,'completed');});
test('手动爆发就绪与生效反馈对应真实代价，暂停冻结',()=>{global.XJ=X;vm.runInThisContext(fs.readFileSync(require.resolve('../scripts/feedback.js'),'utf8').replace(/\}\)\(window\);?\s*$/,'})(globalThis);'));const ui=require('../scripts/experience-ui.js');const r=quiet();r.gift='life';r.life=1;assert.equal(ui.actionClass(r,'lifeAction'),'action-ready');assert(ui.attempt(r,'life'));assert.equal(r.life,0);assert.equal(ui.actionClass(r,'lifeAction'),'action-active');r.state='paused';const b=r.cool.burst;r.step(.05);assert.equal(r.cool.burst,b);assert.equal(ui.actionClass(r,'lifeAction'),'');r.state='running';r.cool.burst=0;assert.equal(ui.actionClass(r,'lifeAction'),'');assert(!ui.attempt(r,'life'));});
console.log(JSON.stringify({suite:'0.15 mountain encounters: unit and constructed regression',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
