'use strict';
const assert=require('node:assert/strict'),{Run,SKILLS,ITEMS,GIFTS,RECIPE,dist}=require('../scripts/content.js');const results=[];
const test=(name,fn)=>{try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}};
function quiet(item='sword'){let r=new Run(703,item);r.spawnTimer=r.eliteAt=r.bossAt=r.eventAt=1e8;r.cool.attack=1e8;return r;}
function enemy(r,x=1700,y=1100,type=0){let e=r.spawn(type,false,x,y);e.born=0;e.hp=e.max=10000;e.speed=0;e.cd=10000;return e;}
function cast(r,id,lv=1,e){r.skills[id]=lv;r.cool[id]=0;r.updateSkills(.016,e||r.nearest());}
function step(r,seconds,input={}){for(let i=0;i<seconds*60;i++)r.step(1/60,input);}
test('规模与原著记录一一对应，类别不混入配方',()=>{const lore=require('../docs/设定资料库.json').records;assert.equal(SKILLS.length,13);assert.equal(GIFTS.length,5);assert.equal(ITEMS.length,5);for(const [kind,arr] of [['神通',SKILLS],['箓气',GIFTS],['器物',ITEMS]])for(const c of arr){let a=lore.find(x=>x.kind===kind&&x.id===c.id);assert(a&&a.sources.length&&a.fact&&a.limit);assert.equal(c.name,a.name);}assert.equal(new Set(SKILLS.map(s=>s.id)).size,13);assert.equal(RECIPE.ids.length,5);});
test('靖平敕近强远弱、等近敌才施放、打断冲锋',()=>{let r=quiet(),near=enemy(r,1650),far=enemy(r,1800);near.phase='dash';cast(r,'thunder',1,near);assert(10000-near.hp>10000-far.hp);assert.equal(near.phase,'move');assert(near.stun>far.stun);let a=quiet(),e=enemy(a,1810);cast(a,'thunder',1,e);assert.equal(a.p.mp,100);assert.equal(e.hp,10000);});
test('镂金石普攻带穿透与破护、击杀后淬炼有上限',()=>{let r=quiet();r.skills.gold=2;let e=enemy(r,1650);e.shield=true;r.autoAttack(e);let b=r.bullets.list()[0];assert.equal(b.pierce,2);r.updateBullets(.08);assert(e.exposed>0);assert(e.hp<9975);for(let i=0;i<60;i++){let x=enemy(r,1680);r.hit(x,1e6);}assert.equal(r.temperKills,30);r.bullets.forEach(b=>r.bullets.remove(b));r.autoAttack(e);assert.equal(r.bullets.list()[0].damage,41);});
test('天金胄逐次承伤、溢出扣血、到期清甲',()=>{let r=quiet(),e=enemy(r);cast(r,'armor',1,e);assert.equal(r.p.armor,38);r.hurt(10);assert.equal(r.p.armor,28);assert.equal(r.p.hp,100);r.p.inv=0;r.hurt(40);assert.equal(r.p.hp,88);assert.equal(r.p.armor,0);r.p.armor=20;r.p.armorTime=.01;step(r,.04);assert.equal(r.p.armor,0);});
test('雉离行定向吐焰：前方受伤、身后不受伤，等级与控火改变表现',()=>{let r=quiet(),front=enemy(r,1700),back=enemy(r,1500);cast(r,'flame',1,front);r.updateZones(.016);assert(front.hp<10000);assert.equal(back.hp,10000);assert(r.moveFactor>1);const a=quiet(),b=quiet();a.gift='firegift';let ea=enemy(a,1700),eb=enemy(b,1700);cast(a,'flame',1,ea);cast(b,'flame',1,eb);a.updateZones(.01);b.updateZones(.01);assert(Math.abs((10000-ea.hp)/(10000-eb.hp)-1.2)<.001);assert(a.p.mp>b.p.mp);});
test('清夕雨持续磨护：初落不瞬间消盾，持续后普攻能接入',()=>{let r=quiet(),e=enemy(r,1700);e.shield=true;cast(r,'rain',1,e);r.updateZones(.016);assert(!e.exposed);let z=r.zones.list().find(z=>z.kind==='rain');z.age=1;z.tick=0;r.updateZones(.016);assert(e.exposed>0);let hp=e.hp;r.hit(e,10);assert(Math.abs(hp-e.hp-10)<.001);});
test('潇重林疗伤有驻地要求，不恢复其他资源与寿元',()=>{let r=quiet();r.p.hp=50;r.p.mp=80;r.life=3;cast(r,'grove',2);let mp=r.p.mp;r.updateZones(1);assert.equal(r.p.hp,54);assert.equal(r.p.mp,mp);assert.equal(r.life,3);r.p.x+=400;r.updateZones(1);assert.equal(r.p.hp,54);let a=quiet();cast(a,'grove');assert.equal(a.p.mp,100);});
test('君蹈危无近敌不凭空疗伤，脱围仅返还此战有限部分',()=>{let r=quiet();r.skills.body=3;r.p.hp=60;step(r,4);assert.equal(r.p.hp,60);for(let i=0;i<5;i++)enemy(r,1670,1070+i*8);r.updateSkills(.01,r.nearest());r.hurt(10);let hp=r.p.hp,owed=r.p.battleWounds;r.enemies.forEach(e=>r.enemies.remove(e));step(r,10);assert(Math.abs(r.p.hp-hp-owed)<.00001);assert(r.p.hp<60);assert.equal(r.p.battleWounds,0);});
test('赤断镞不凭空伤敌、不爆炸，离域返还实际掉血的一分',()=>{let r=quiet(),e=enemy(r,1660);cast(r,'dusk',1,e);r.updateZones(.1);assert.equal(e.hp,10000);r.hurt(20);assert.equal(r.p.hp,80);let z=r.zones.list()[0];assert(Math.abs(z.playerWound-4.8)<.001);r.hit(e,100);e.x=1950;r.p.x=1950;r.updateZones(.1);assert(Math.abs(r.p.hp-84.8)<.001);assert(Math.abs(e.hp-9924)<.001);z.age=z.life-.01;const hp=e.hp;r.updateZones(.02);assert.equal(e.hp,hp);r.updateZones(.1);assert(Math.abs(r.p.hp-84.8)<.001);});
test('血漠不返还护甲挡住的伤害，也不能复活',()=>{let r=quiet(),e=enemy(r);cast(r,'dusk',1,e);r.p.armor=40;r.p.armorTime=4;r.hurt(20);assert.equal(r.zones.list()[0].playerWound,0);r.p.inv=0;r.p.armor=0;r.p.hp=5;r.hurt(20);r.p.x=2000;r.updateZones(.2);assert.equal(r.state,'ended');assert.equal(r.p.hp,0);});
test('仙无漏连续降法只消灵力来袭，地面护行保留',()=>{let r=quiet(),e=enemy(r);r.hazard(1600,1100);cast(r,'pure',1,e);let metal=r.shoot(1660,1100,1600,1100,12,true,0,200,2,'metal'),spirit=r.shoot(1650,1100,1600,1100,12,true);r.updateBullets(.016);assert(metal.active);assert(!spirit.active);assert(r.p.guard>0);assert(!r.zones.list().some(z=>z.kind==='hazard'));});
test('五种受箓一次择一，按键索引有效且不占神通',()=>{for(let i=0;i<5;i++){let r=quiet();r.openChoice('gift');assert.equal(r.choices.length,5);let mp=r.p.mp;r.step(1);assert.equal(r.p.mp,mp);assert(r.choose(i));assert.equal(r.gift,GIFTS[i].id);assert.equal(Object.keys(r.skills).length,0);r.giftPending=true;r.nextChoice();assert.equal(r.state,'running');}});
test('长空危雀实际伤血才悍勇，护甲与无敌不触发，暂停冻结',()=>{let r=quiet();r.gift='sparrow';r.p.armor=20;r.p.armorTime=3;r.hurt(10);assert(!r.cool.brave);r.p.inv=0;r.p.armor=0;r.hurt(10);assert.equal(r.cool.brave,5);assert.equal(r.power,1.25);assert.equal(r.moveFactor,1.2);r.pause();step(r,2);assert.equal(r.cool.brave,5);r.pause();step(r,5.1);assert.equal(r.power,1);});
test('行气吞灵驾雾付费免地面，非无敌、不可连发',()=>{let r=quiet();r.gift='cloud';assert.equal(r.regen,10);r.p.mp=11;assert(!r.giftUse());assert.equal(r.p.mp,11);r.p.mp=30;assert(r.giftUse());assert.equal(r.p.mp,18);assert(!r.giftUse());r.hurt(15,true);assert.equal(r.p.hp,100);r.hurt(12,false);assert.equal(r.p.hp,88);});
test('谷风引火不授予火法，实际费用低于原价边界仍可施放',()=>{let r=quiet('bow');r.gift='firegift';enemy(r);r.p.mp=19.36;assert(r.itemUse());assert(Math.abs(r.p.mp)<1e-8);assert.equal(Object.keys(r.skills).length,0);r.cool.item=0;r.p.mp=19.35;assert(!r.itemUse());assert.equal(r.p.mp,19.35);});
test('坎金环群体束缚并终止冲锋，不伤害冒充重武器',()=>{let r=quiet('rings'),a=enemy(r),b=enemy(r,1730);a.phase='dash';assert(r.itemUse());assert.equal(a.root,2.4);assert.equal(a.phase,'move');assert.equal(b.root,2.4);let x=a.x;r.updateEnemies(.1);assert.equal(a.x,x);assert.equal(a.hp,10000);});
test('八面屏只定金属箭，离屏释放，无无条件全弹免疫',()=>{let r=quiet('screen');assert(r.itemUse());let metal=r.shoot(1640,1100,1600,1100,12,true,0,200,2,'metal'),spirit=r.shoot(1640,1120,1600,1120,12,true);r.updateBullets(.05);assert.equal(metal.x,1640);assert(spirit.x<1640);assert(metal.held>0);r.zones.forEach(z=>r.zones.remove(z));metal.held=0;r.updateBullets(.05);assert(metal.x<1640);});
test('六角盏加持真火且削金箭一次，不削灵力弹',()=>{let r=quiet('lamp');enemy(r);assert(r.itemUse());let a=r.shoot(1700,1100,1900,1100,20,true,0,200,3,'metal'),b=r.shoot(1700,1100,1900,1100,20,true);r.intercept();assert.equal(a.damage,8);assert.equal(b.damage,20);r.intercept();assert.equal(a.damage,8);assert.equal(r.firePower(),1.15);r.gift='firegift';assert(Math.abs(r.firePower()-1.38)<.001);});
test('新状态结算与重开清空，所有新增神通仍可跨道',()=>{let r=quiet('lamp');for(const s of SKILLS)r.skills[s.id]=3;r.p.armor=30;r.temperKills=25;r.cool.cloud=2;r.gift='cloud';assert(r.recipe());r.end();let fresh=new Run(r.seed,r.item);assert.equal(fresh.p.armor,0);assert.equal(fresh.temperKills,0);assert.equal(fresh.gift,null);assert(!fresh.cool.cloud);});
console.log(JSON.stringify({suite:'0.2 logic and constructed simulation',passed:results.filter(x=>x.pass).length,total:results.length,results},null,2));process.exitCode=results.every(x=>x.pass)?0:1;
