'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const X=require('../scripts/field-event.js');const UI=require('../scripts/experience-ui.js');
const context={window:{XJ:X}};vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/feedback.js'),'utf8'),context);global.XJFeedback=context.window.XJFeedback;
const results=[];function test(name,f){try{f();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
function quiet(item='sword'){let r=new X.Run(42,item,'standard');r.spawnTimer=r.eliteAt=r.bossAt=r.eventAt=1e8;r.autoItem=false;r.cool.attack=1e8;return r;}
test('presentation does not change offers, RNG, resources or learned skills',()=>{const a=quiet(),b=quiet();a.skills={gate:1};b.skills={gate:1};for(const s of X.SKILLS){UI.benefit(s.id,1);UI.relation(a,s.id);UI.routes(a);UI.card(a,s.id,0,()=>'',{},{});}assert.equal(a.random(),b.random());assert.deepEqual(a.skills,b.skills);assert.equal(a.p.mp,b.p.mp);assert.deepEqual(a.offer(),b.offer());});
test('every learnable skill and gift retains a cost/condition and complete detail without undefined',()=>{const r=quiet();for(const kind of ['upgrade','gift']){r.choiceKind=kind;for(const s of kind==='gift'?X.GIFTS:X.SKILLS){const html=UI.card(r,s.id,0,()=>'',{},{});assert(!html.includes('undefined'));assert(html.includes(s.name));assert(html.includes(s.desc));assert(html.includes('<details'));assert(html.includes('decision-cost'));}}});
test('screen shows ineffective spring strengthening and no false damage synergy',()=>{const r=quiet('screen');r.skills={spring:1,gold:1,gate:1};assert.match(UI.fit(r,'spring'),/强化暂无收益/);assert(!UI.relation(r,'spring').includes('强化伤害普攻'));assert.match(UI.fit(r,'edict'),/无普攻追加/);});
test('visible limitations retain dusk enemy restoration, lethal boundary and life permanent cost',()=>{const r=quiet();assert.match(UI.card(r,'dusk',0,()=>'',{},{}),/敌人也会返伤，致死不救/);assert.match(UI.card(r,'dusk',0,()=>'',{},{}),/8 法力/);r.choiceKind='gift';assert.match(UI.card(r,'life',0,()=>'',{},{}),/不可恢复/);assert.match(UI.card(r,'firegift',0,()=>'',{},{}),/雉离行/);});
test('card mastery delta matches actual rain follow and spring charges',()=>{for(const id of ['rain','spring']){const r=quiet();r.skills[id]=2;r.openChoice();r.choices=[id];assert(r.choose(0));const e=r.spawn(0,false,r.p.x+80,r.p.y);e.born=0;r.cool[id]=0;r.updateSkills(.01,e);if(id==='spring'){assert.equal(r.springCharges,6);assert.match(UI.benefit(id,2),/两次/);}else{assert.equal(r.zones.list()[0].lv,3);assert.match(UI.benefit(id,2),/随身缓移/);}}});
test('dusk attempted outside field explains failure without cost; inside uses real blink',()=>{const r=quiet();r.skills.dusk=1;assert(!UI.attempt(r,'blink'));assert.match(r.message,/血漠/);assert.equal(r.p.mp,100);r.zones.add({kind:'dusk',x:r.p.x,y:r.p.y,r:250,age:0,life:6});assert(UI.attempt(r,'blink'));assert.equal(r.p.mp,92);assert.equal(r.telemetry.blinkUses,1);assert(!UI.attempt(r,'blink'));assert.equal(r.p.mp,92);assert.match(r.message,/冷却/);});
test('manual waiting reports missing target before suggesting mana; primary shows exact shortfall',()=>{const r=quiet();r.skills={gate:1};r.cool.gate=0;r.p.mp=0;r.setPrimary('gate');assert.equal(global.XJFeedback.state(r,'gate'),'等待目标');const e=r.spawn(0,false,r.p.x+80,r.p.y);e.born=0;r.updateSkills(.01,e);assert.match(global.XJFeedback.state(r,'gate'),/蓄法.*26/);});
test('limited HUD retains primary, manual and dusk with full-catalog access',()=>{const r=quiet();r.skills=Object.fromEntries(X.SKILLS.map(s=>[s.id,1]));r.setPrimary('gate');r.setManual('rain');const html=UI.loadout(r,'gold',0);assert.equal((html.match(/skill-live/g)||[]).length,4);for(const name of ['谒天门','清夕雨','赤断镞','全部 19 法'])assert(html.includes(name));});
test('growth distinguishes actual new fruit and ordinary mastery without adding a reward',()=>{const r=quiet();r.skills={gate:3};assert.match(UI.growth(r,'gate',{}),/三重/);r.fruits.mingyang=true;assert.match(UI.growth(r,'gate',{}),/明阳果位已成/);assert.equal(r.p.mp,100);assert.equal(r.extraPower,0);});
test('life exhausted/cooling attempts have readable feedback and never spend extra life',()=>{const r=quiet();r.gift='life';r.life=0;assert(!UI.attempt(r,'life'));assert.match(r.message,/寿元已尽/);r.life=8;assert(UI.attempt(r,'life'));assert.equal(r.life,7);assert(!UI.attempt(r,'life'));assert.equal(r.life,7);assert.match(r.message,/冷却/);});
console.log(JSON.stringify({suite:'playtest presentation and action regression',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
