'use strict';
const assert=require('node:assert/strict'),{Run,FoundationDuel,dist}=require('../scripts/field-event.js'),results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
function run(){const r=new Run(42,'bow','standard');r.dao='mingyang';r.skills.gate=2;r.level=5;r.t=60;r.spawnTimer=r.eliteAt=1e9;return r;}
function boss(r){r.updateFoundationDuel();const e=r.duelEnemy();assert(e);e.born=0;e.x=r.p.x+240;e.y=r.p.y;return e;}
function enemies(r,s){for(let i=0;i<Math.round(s/.05);i++)r.updateEnemies(.05);}
test('normal step schedules a foundation opponent and replaces the first ordinary boss slot',()=>{const r=run();r.step(.05,{});const e=r.duelEnemy();assert.equal(e.duelId,'yumuxian');assert.equal(r.bossAt,360);assert.equal(r.duelSeen,undefined);assert.equal(r.duelHistory.length,1);assert.equal(r.realm,'筑基');assert.equal(e.max,560);r.updateFoundationDuel();assert.equal(r.enemies.count,1);});
test('eligibility guards: level, realm, time and occupied boss; unavailable pool retries without consuming encounter',()=>{
 for(const f of [r=>r.level=4,r=>r.skills.gate=3,r=>r.t=180,r=>r.dao=null,r=>r.spawn(6)]){const r=run();f(r);r.updateFoundationDuel();assert(!r.foundationDuelSeen);assert.equal(r.bossAt,180);}
 const r=run();for(let i=0;i<160;i++)r.enemies.add({type:0});r.updateFoundationDuel();assert(!r.foundationDuelSeen);r.enemies.remove(r.enemies.list()[0]);r.updateFoundationDuel();assert(r.foundationDuelSeen);assert.equal(r.enemies.count,160);
});
test('finite shield absorbs damage, overflow reaches HP and break cancels attack with recovery',()=>{
 const r=run(),e=boss(r),n=200,damage=n*r.power*r.enemyDamageMultiplier(e,false);r.startDuelCast(e,'spindles');r.hit(e,n);assert.equal(e.duelShield,0);assert(Math.abs(e.hp-(e.max-(damage-120)))<1e-8);assert.equal(e.phase,'move');assert.equal(e.duelShots.length,0);assert.equal(e.recover,2.5);assert.equal(r.bullets.count,0);
});
test('half health triggers lotus once, clears pending shots, cannot refill indefinitely',()=>{const r=run(),e=boss(r);e.duelShield=0;e.hp=270;r.startDuelCast(e,'spindles');r.updateEnemies(.05);assert.equal(e.duelPhase,2);assert.equal(e.duelShield,96);assert.equal(r.duelHistory[0].phase,2);assert.equal(e.duelShots.length,0);r.hit(e,130);assert.equal(e.duelShield,0);enemies(r,3);assert.equal(e.duelShield,0);assert.equal(e.duelPhase,2);});
test('eight spindles use locked origins and angles, wait for warning, carry damage attribution',()=>{const r=run(),e=boss(r);r.startDuelCast(e,'spindles');const shots=e.duelShots.map(q=>({...q}));r.p.y+=220;enemies(r,1.4);assert.equal(r.bullets.count,0);enemies(r,.15);const bs=r.bullets.list();assert.equal(bs.length,8);bs.forEach((b,i)=>{assert.equal(b.x,shots[i].x);assert.equal(b.y,shots[i].y);assert(Math.abs(b.vx-shots[i].ax*185)<1e-8);assert.equal(b.source.name,'郁慕仙 · 菱形法器');assert.equal(b.duelId,e.id);});});
test('foundation muddle can interrupt pending spindles without a phantom release',()=>{const r=run(),e=boss(r);r.dao='lushui';r.skills={muddle:2};e.x=r.p.x+100;r.startDuelCast(e,'spindles');r.updateSkills(.05,e);assert.equal(e.phase,'move');enemies(r,.3);assert.equal(r.bullets.count,0);});
test('pause/choice/ended never advance the foundation encounter',()=>{for(const state of ['paused','choice','ended']){const r=run(),e=boss(r);r.startDuelCast(e,'spindles');r.state=state;const before=JSON.stringify([r.t,e.timer,r.duelHistory]);r.step(.05,{});assert.equal(JSON.stringify([r.t,e.timer,r.duelHistory]),before);}});
test('a normal breakthrough remains available during the fight and does not upgrade the enemy realm',()=>{const r=run(),e=boss(r);r.level=7;r.state='choice';r.choiceKind='upgrade';r.choices=['gate'];assert(r.choose(0));assert.equal(r.realm,'紫府');assert.equal(e.title,'郁慕仙 · 筑基后期');assert.equal(e.max,560);});
test('two opponents retain independent history and rewards; repeating damage does not duplicate rewards',()=>{const r=run(),e=boss(r);r.hit(e,1e9);assert.equal(r.bosses,1);assert.equal(r.rerolls,2);r.hit(e,1e9);assert.equal(r.rerolls,2);r.t=360;r.skills.gate=3;const y=r.spawn(6);assert.equal(y.duelId,'yehui');y.born=0;y.hp=y.max*.5;r.updateEnemies(.05);assert.equal(r.duelHistory[0].phase,1);assert.equal(r.duelHistory[1].phase,2);r.hit(y,1e9);assert.deepEqual(r.duelHistory.map(x=>[x.id,x.defeatedAt]),[['yumuxian',60],['yehui',360]]);assert.equal(r.bosses,2);r.end('主动结束');assert.equal(r.result.duelHistory.length,2);});
test('mixed encounter cast telemetry remains finite across all three attacks',()=>{const r=run(),e=boss(r);r.startDuelCast(e,'spindles');r.hit(e,1e9);r.t=360;r.skills.gate=3;const y=r.spawn(6);r.startDuelCast(y,'mountain');r.startDuelCast(y,'water');assert.deepEqual(r.telemetry.duelCasts,{spindles:1,mountain:1,water:1});});
test('undefeated foundation boss retires before terminal without a false defeat or remaining spells',()=>{const r=run(),e=boss(r);r.startDuelCast(e,'spindles');enemies(r,1.6);assert.equal(r.bullets.count,8);r.t=674.99;r.step(.05,{});assert(!e.active);assert(r.enemies.list().some(q=>q.final&&!q.duelId));assert.equal(r.duelHistory[0].defeatedAt,null);assert(!r.bullets.list().some(b=>b.duelId===e.id));assert.equal(r.rerolls,0);});
test('all four paths can walk away from locked eight-spindle trajectories without spells or dash',()=>{for(const dao of ['mingyang','lushui','lihuo','duijin']){const r=run(),e=boss(r);r.dao=dao;r.skills={};r.startDuelCast(e,'spindles');const hp=r.p.hp;for(let i=0;i<84;i++){r.p.y+=180*.05;r.updateEnemies(.05);r.updateBullets(.05);}assert.equal(r.p.hp,hp,dao);}});
console.log(JSON.stringify({suite:'foundation duel constructed contracts',passed:results.filter(x=>x.pass).length,total:results.length,results},null,2));process.exitCode=results.every(x=>x.pass)?0:1;
