const assert=require('assert/strict'),X=require('../scripts/field-event.js');const tests=[];function test(name,f){try{f();tests.push({name,pass:true});}catch(e){tests.push({name,pass:false,error:e.stack});}}
const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function run(active=true){const r=new X.Run(42,'bow','standard');r.skills={light:3};r.autoItem=false;r.spawnTimer=r.bossAt=r.eliteAt=r.eventAt=1e9;r.cool.attack=r.cool.light=1e9;if(active){r.fruits.mingyang=true;r.fruit=true;r.fruitEnergy=0;}return r;}
function enemy(r,x=200){const e=r.spawn(0,false,r.p.x+x,r.p.y);e.born=0;e.hp=e.max=1e8;e.speed=0;e.cd=1e9;return e;}
function ticks(r,n){for(let i=0;i<n*20;i++)r.step(.05);}
test('locked F cannot spend or fire; formation fills once and returns manual to auto',()=>{const r=run(false);r.setManual('light');assert(!r.castFruitActive());r.skills={gate:3,body:1,edict:1,dusk:1};r.state='choice';r.choices=['light'];r.choiceKind='upgrade';assert(r.choose(0));assert(r.hasFruitActive());near(r.fruitActiveEnergy(),100);assert.equal(r.manualSkill,null);assert(!r.setManual('light'));assert(r.castFruitActive());r.state='choice';r.choices=['rain'];r.choose(0);near(r.fruitActiveEnergy(),0);});
test('combat time fills in 40 seconds; safe distance, pause, choice and death do not charge',()=>{const r=run();enemy(r);ticks(r,40);near(r.fruitActiveEnergy(),100);r.fruitEnergy=0;r.enemies.list().forEach(e=>r.enemies.remove(e));ticks(r,1);near(r.fruitActiveEnergy(),0);enemy(r,1000);ticks(r,1);near(r.fruitActiveEnergy(),0);enemy(r);for(const state of ['paused','choice','ended']){r.state=state;ticks(r,1);near(r.fruitActiveEnergy(),0);}r.state='running';r.p.hp=0;r.updateZones(.05);near(r.fruitActiveEnergy(),0);});
test('kill bonus capped per cycle, dead enemies cannot be counted twice',()=>{const r=run();for(let i=0;i<5;i++){const e=enemy(r);e.elite=true;e.hp=1;r.hit(e,5,true);r.hit(e,5,true);}near(r.fruitActiveEnergy(),12);near(r.fruitKillEnergy,12);});
test('full charge held indefinitely; insufficient charge harmless; full cast free of mana and not repeatable',()=>{const r=run();enemy(r);r.fruitEnergy=99;r.p.mp=0;assert(!r.castFruitActive());near(r.fruitEnergy,99);r.fruitEnergy=100;r.enemies.list().forEach(e=>r.enemies.remove(e));ticks(r,2);near(r.fruitEnergy,100);r.p.mp=0;assert(r.castFruitActive());near(r.p.mp,0);near(r.fruitEnergy,0);assert(!r.castFruitActive());assert.equal(r.telemetry.fruitActives,1);r.updateZones(.6);r.updateZones(.6);assert.equal(r.telemetry.edictPulses,3);});
test('ordinary light remains single pulse even with fruit; active does not spend ordinary cooldown',()=>{const r=run();const e=enemy(r);r.cool.light=0;r.p.mp=100;r.updateSkills(.01,e);near(e.max-e.hp,38);assert(!r.lightEdict);near(r.p.mp,74);r.fruitEnergy=100;assert(r.castFruitActive());near(r.cool.light,8);near(r.p.mp,74);near(e.max-e.hp,76);});
test('pause freezes echoes; restart clears and endless keeps charge',()=>{const r=run();r.fruitEnergy=100;assert(r.castFruitActive());r.pause();ticks(r,1);near(r.lightEdict.age,0);r.pause();r.fruitEnergy=61;r.end('破阵功成');assert(r.continueEndless());near(r.fruitEnergy,61);const fresh=new X.Run();assert(!fresh.hasFruitActive());near(fresh.fruitActiveEnergy(),0);});
console.log(JSON.stringify({passed:tests.filter(t=>t.pass).length,total:tests.length,results:tests},null,2));if(tests.some(t=>!t.pass))process.exitCode=1;
