'use strict';
const assert=require('node:assert/strict'),X=require('../scripts/field-event.js'),UI=require('../scripts/experience-ui.js');
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function run(){const r=new X.Run(42,'bow','standard');r.level=2;r.spawnTimer=r.eliteAt=r.bossAt=1e8;r.autoItem=false;return r;}
function pick(r,id){r.openChoice();r.choices=[id];assert(r.choose(0));}
function enemy(r,type=0){const e=r.spawn(type,false,r.p.x+20,r.p.y);e.born=0;e.hp=e.max=10000;e.speed=0;return e;}
function cast(r,id,e){r.setManual(id);r.cool[id]=0;r.p.mp=100;r.updateSkills(.01,e,true);}
test('five at one never forms; any route skill at three forms exactly once; off-route mastery/training does not count',()=>{for(const recipe of X.RECIPES){const r=run();for(const id of recipe.ids)pick(r,id);assert(!r.fruits[recipe.id]);pick(r,'armor');pick(r,'armor');pick(r,'armor');pick(r,'vigor');assert(!r.fruits[recipe.id]);pick(r,recipe.ids[0]);assert(!r.fruits[recipe.id]);pick(r,recipe.ids[0]);assert(r.fruits[recipe.id]);assert.equal(r.fx.list().filter(f=>f.kind==='fruit').length,1);pick(r,recipe.ids[1]);assert.equal(r.fx.list().filter(f=>f.kind==='fruit').length,1);}});
test('mastery first then fifth skill forms; independent routes can coexist',()=>{const r=run();for(const recipe of X.RECIPES){pick(r,recipe.ids[0]);pick(r,recipe.ids[0]);pick(r,recipe.ids[0]);for(const id of recipe.ids.slice(1))pick(r,id);assert(r.fruits[recipe.id]);}assert.equal(Object.keys(r.fruits).length,2);});
test('cards distinguish fifth skill from actual formation and second-to-third mastery',()=>{const r=run();r.skills={gate:1,body:1,edict:1,dusk:1};assert(!UI.relation(r,'light').includes('选后成型'));r.skills.light=1;assert(UI.routes(r).includes('任一同参修至三重'));r.skills.gate=2;assert(UI.relation(r,'gate').includes('选后成型'));assert(!UI.relation(r,'vigor').includes('成型'));});
test('1000 seeds: full route mastery pity preserves two skills plus training and supplies a route upgrade',()=>{for(let seed=0;seed<1000;seed++){const r=new X.Run(seed,'bow','standard');r.level=2;r.skills=Object.fromEntries(X.RECIPE.ids.map(id=>[id,1]));r.offerMisses={mingyang:3};r.openChoice();assert.equal(r.choices.filter(id=>X.SKILLS.some(s=>s.id===id)).length,2);assert(r.choices.some(id=>X.RECIPE.ids.includes(id)));assert.equal(r.offerMisses.mingyang,0);}});
test('edict hits three times at the cast point, clears new bullets, no general or extra mana',()=>{const r=run(),e=enemy(r);r.skills={light:3};r.fruit=true;r.fruits.mingyang=true;r.fruitEnergy=100;r.castFruitActive();near(r.p.mp,100);near(e.hp,9962);assert.equal(r.allies.count,0);assert.equal(r.telemetry.edictPulses,1);const origin={x:r.p.x,y:r.p.y};r.p.x+=600;r.shoot(origin.x,origin.y,origin.x+50,origin.y,5,true);r.updateZones(.59);near(e.hp,9962);r.updateZones(.01);near(e.hp,9924);assert.equal(r.bullets.count,0);r.updateZones(.6);near(e.hp,9886);assert.equal(r.telemetry.edictPulses,3);assert(!r.lightEdict);near(r.p.mp,100);r.updateZones(2);near(e.hp,9886);});
test('full pools cannot displace edict echoes; ordinary light has one pulse and original radius',()=>{const r=run(),e=enemy(r);r.skills={light:1};for(let i=0;i<8;i++)r.allies.add({x:r.p.x,y:r.p.y,life:8,cd:1,empowered:0});while(r.zones.count<r.zones.max)r.zones.add({kind:'unused',x:0,y:0,r:1,age:0,life:10,tick:0});r.fruit=true;r.fruits.mingyang=true;r.fruitEnergy=100;r.castFruitActive();r.updateZones(1.2);assert.equal(r.telemetry.edictPulses,3);assert.equal(r.allies.count,8);assert(r.allies.list().every(a=>!a.general));const b=run(),q=enemy(b);b.skills={light:1};cast(b,'light',q);b.updateZones(1.2);near(q.hp,9978);assert(!b.lightEdict);assert.equal(b.allies.count,0);});
test('fruit rain multiplies radius duration and actual damage at all three levels including screen',()=>{for(const lv of [1,2,3]){for(const fruit of [false,true]){const r=run(),e=enemy(r);r.item='screen';r.skills.rain=lv;r.fruits.lushui=fruit;cast(r,'rain',e);const z=r.zones.list()[0];near(z.r,(110+lv*20)*(fruit?1.25:1));near(z.life,(4+lv*.5)*(fruit?1.35:1));const hp=e.hp;r.updateZones(.01);near(hp-e.hp,(6+lv*3)*(fruit?1.5:1));near(r.p.mp,78);}}});
test('two seconds continuous rain breaks guard for three seconds after leaving; never removes innate armor or bullets',()=>{const r=run(),e=enemy(r,5);e.shield=true;r.skills.rain=3;r.fruits.lushui=true;cast(r,'rain',e);r.bullets.add({enemy:true,life:10});for(let i=0;i<39;i++)r.updateZones(.05);assert(!(e.rainBroken>0));r.updateZones(.05);assert(e.rainBroken>0);near(r.enemyDamageMultiplier(e),.6);e.x=3000;e.exposed=0;r.updateZones(.05);assert(e.rainBroken>0);assert.equal(e.rainPressure,0);for(let i=0;i<61;i++)r.updateZones(.05);assert.equal(e.rainBroken,0);near(r.enemyDamageMultiplier(e),.4);assert.equal(r.bullets.count,1);});
test('overlap cannot double soak speed; leaving before two seconds resets it',()=>{const r=run(),e=enemy(r);e.shield=true;for(let i=0;i<2;i++)r.zones.add({kind:'rain',fruitRain:true,lv:1,x:e.x,y:e.y,r:100,age:0,life:10,tick:0});for(let i=0;i<20;i++)r.updateZones(.05);assert(!(e.rainBroken>0));near(e.rainSoak,1);e.x=3000;r.updateZones(.05);assert.equal(e.rainSoak,0);});
test('pause freezes fruit combat effects, restart resets, old saved fruit achievements survive import',()=>{const r=run();r.skills={gate:3,light:1};r.fruit=true;r.fruits.mingyang=true;r.fruitEnergy=100;r.castFruitActive();r.pause();r.step(.05);near(r.lightEdict.age,0);r.state='running';r.end('破阵功成');assert(r.result.fruits.mingyang);assert(r.continueEndless());assert(r.fruit);assert.equal(new X.Run().allies.count,0);assert.deepEqual(new X.Run().fruits,{});const vm=require('node:vm'),fs=require('node:fs'),w={XJ:X};vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),{window:w,localStorage:{getItem:()=>null,setItem:()=>{}},Date,Math,Set,Map,WeakMap});w.XJArchive.merge({schema:1,records:[{id:'legacy-fruit',item:'bow',time:300,version:'0.16.0',fruits:{mingyang:true},skills:Object.fromEntries(X.RECIPE.ids.map(id=>[id,1]))}]});assert(w.XJArchive.data.records[0].fruits.mingyang);});
console.log(JSON.stringify({suite:'0.17 fruit: unit and constructed checks, not normal play',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
