'use strict';
const assert=require('node:assert/strict');const X=require('../scripts/field-event.js');const results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
function run(gift,item='bow'){const r=new X.Run(1,item);r.gift=gift;r.spawnTimer=r.eliteAt=r.bossAt=9999;return r;}
function enemy(r,dx=60,hp=1000){const e=r.spawn(0,false,r.p.x+dx,r.p.y);e.born=0;e.hp=e.max=hp;return e;}
test('six current definitions, historical lookup, eligibility and one talisman',()=>{assert.equal(X.GiftSystem.definitions.length,6);assert(X.GiftSystem.get('might'));assert(!X.GiftSystem.available(run(null),'might'));const r=run(null);r.openChoice('gift');assert(r.choices.includes('frostpine'));assert(!r.choices.includes('greed'));r.choices=['greed'];assert.equal(r.choose(0),false);r.dao='lihuo';r.skills.dali=3;r.openChoice('gift');assert.equal(r.choices.length,6);assert(r.choices.includes('frostpine'));assert(r.choices.includes('greed'));assert(r.choose(r.choices.indexOf('greed')));r.openChoice('gift');assert.equal(r.choose(0),false);const s=run(null,'thunderseal');s.openChoice('gift');assert(!s.choices.includes('might'));});
test('defer preserves progression; next elite reopens without stacking',()=>{const r=run(null);r.openChoice('gift');assert(r.deferGift());assert.equal(r.gift,null);assert.equal(r.state,'running');assert(!r.deferGift());const e=enemy(r,50,1);e.elite=true;r.hit(e,100);r.nextChoice();assert.equal(r.choiceKind,'gift');assert(r.choose(r.choices.indexOf('frostpine')));assert.equal(r.gift,'frostpine');});
test('might strengthens bow base but not extra spells or direct spell damage',()=>{const a=run(null),b=run('might');for(const r of [a,b]){const e=enemy(r);r.autoAttack(e);}assert.equal(a.bullets.list()[0].damage,23);assert(Math.abs(b.bullets.list()[0].damage-29.9)<1e-10);const e=enemy(b);const hp=e.hp;b.hit(e,10);assert.equal(hp-e.hp,10);});
test('might spear and dasheng base scaling excludes attached spell',()=>{for(const item of ['spear','dasheng']){const a=run(null,item),b=run('might',item);const ea=enemy(a),eb=enemy(b);a.autoAttack(ea);b.autoAttack(eb);assert(Math.abs((1000-eb.hp)/(1000-ea.hp)-1.3)<1e-10);}});
test('sparrow requires actual nearby bloodshed and cannot refresh continuously',()=>{const r=run('sparrow');const e=enemy(r,220);r.hit(e,1);assert(!r.cool.brave);e.x=r.p.x+50;e.born=1;r.hit(e,1);assert(!r.cool.brave);e.born=0;r.hit(e,1);assert.equal(r.cool.brave,5);r.cool.brave=2;r.hit(e,1);assert.equal(r.cool.brave,2);r.p.inv=0;r.hurt(1);assert.equal(r.cool.brave,2);assert.equal(r.giftStats['悍勇'],1);});
test('rainbow only successful casting starts bounded dispel; hazards survive',()=>{const r=run('rainbow');r.skills.rain=1;r.cool.rain=0;const e=enemy(r);r.updateSkills(0,e);assert.equal(r.cool.giftUnweave,.8);for(let i=0;i<3;i++)r.shoot(r.p.x+50,r.p.y,r.p.x,r.p.y,1,true);r.hazard(r.p.x,r.p.y,50,1,3);r.updateBullets(0);assert.equal(r.bullets.count,1);assert.equal(r.zones.count,1);assert.equal(r.giftStats['化解飞弹'],2);r.giftCast();assert.equal(r.giftUnweaveLeft,0);const s=run('rainbow');s.skills.rain=1;s.p.mp=0;s.cool.rain=0;s.updateSkills(0,enemy(s));assert(!s.cool.giftUnweave);});
test('omen predicts incoming path, ignores receding projectiles, freezes in pause',()=>{const r=run('omen');const b=r.shoot(r.p.x+100,r.p.y,r.p.x,r.p.y,1,true,0,200);r.updateGiftThreat();assert.equal(r.giftThreat.kind,'飞弹');b.vx=200;r.updateGiftThreat();assert.equal(r.giftThreat,null);r.state='paused';const t=r.t;r.step(.05);assert.equal(r.t,t);});
test('frostpine shortens hazard pain but never reduces damage or grants invulnerability',()=>{const a=run(null),b=run('frostpine');for(const r of [a,b]){r.hazard(r.p.x,r.p.y,50,0,3);r.updateZones(.05);}assert.equal(a.p.hp,b.p.hp);assert.equal(a.p.slow,1.2);assert.equal(b.p.slow,.45);assert.equal(b.p.recoil,0);assert.equal(a.p.inv,b.p.inv);});
test('greed buffs heartfire only, harvest capped, no life steal or lifespan increase',()=>{const r=run('greed');r.skills.dali=3;r.dao='lihuo';r.p.hp=50;const e=enemy(r);r.heartfireGiftDamage(e,10);assert.equal(1000-e.hp,13);const e2=enemy(r,60,1),e3=enemy(r,70,1);r.heartfireGiftDamage(e2,20);r.heartfireGiftDamage(e3,20);assert.equal(r.giftStats['心火助修'],1);assert.equal(r.p.hp,50);assert.equal(r.life,8);const e4=enemy(r);r.hit(e4,10);assert.equal(1000-e4.hp,10);});
test('life manual cost and exhausted refusal unchanged',()=>{const r=run('life');r.p.mp=0;assert(r.giftUse());assert.equal(r.life,7);assert.equal(r.p.mp,80);assert(!r.giftUse());r.cool.life=0;r.life=0;assert(!r.giftUse());});
test('archive preserves old records and all five new gift ids',()=>{const fs=require('fs'),vm=require('vm');let saved='';const w={XJ:X,localStorage:{getItem:()=>null,setItem:(k,v)=>saved=v},Date,Math};w.window=w;vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),w);w.XJArchive.merge({schema:1,records:[{id:'legacy',item:'bow',time:100,kills:20,fruits:{mingyang:true},skills:{gate:3},gift:'whale'}],marks:['fruit:mingyang'],best:{}});for(const id of ['might','omen','rainbow','frostpine','greed']){const r=run(id);r.seed+=X.GiftSystem.definitions.findIndex(d=>d.id===id);r.end('主动结束');w.XJArchive.record(r);}const data=JSON.parse(saved);assert(data.records.some(r=>r.id==='legacy'&&r.fruits.mingyang));for(const id of ['might','omen','rainbow','frostpine','greed'])assert(data.records.some(r=>r.gift===id),id);});
test('formed heartfire zone uses greed hook and third-rank casting opens rainbow window',()=>{const a=run(null),b=run('greed');for(const r of [a,b]){r.skills.dali=3;r.dao='lihuo';r.cool.dali=0;enemy(r);r.updateSkills(0,r.nearest(r.p,200));assert(r.zones.list().some(z=>z.kind==='dali'));r.updateZones(.05);}assert(Math.abs((1000-b.enemies.list()[0].hp)/(1000-a.enemies.list()[0].hp)-1.3)<1e-9);const c=run('rainbow');c.skills.dali=3;c.dao='lihuo';c.cool.dali=0;c.updateSkills(0,enemy(c));assert.equal(c.cool.giftUnweave,.8);});
console.log(JSON.stringify({suite:'gifts (constructed)',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
