// Browser emulation and constructed choice states; not a real phone benchmark.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{fs.mkdirSync('../gift-browser',{recursive:true});const browser=await chromium.launch({headless:true}),results=[];
for(const [w,h] of [[320,568],[390,844],[844,390],[1440,900]]){const page=await browser.newPage({viewport:{width:w,height:h},isMobile:w!==1440,hasTouch:w!==1440});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:18746/?test');await page.locator('[data-item="bow"]').click();await page.locator('[data-choice="0"]').click();await page.waitForFunction(()=>xuanjian.run.state==='running');
await page.evaluate(()=>{const r=xuanjian.run;r.openChoice('gift');});await page.waitForSelector('[data-gift-confirm]');assert.equal(await page.locator('.gift-choice-card').count(),3);await page.locator('.gift-choice-card').first().click();assert.equal(await page.evaluate(()=>xuanjian.run.gift),null);assert.equal(await page.evaluate(()=>xuanjian.run.state),'choice');assert(await page.locator('[data-gift-confirm]').isEnabled());await page.waitForTimeout(550);await page.screenshot({path:`../gift-browser/choice-${w}.png`});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'horizontal overflow');const t=await page.evaluate(()=>xuanjian.run.t);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>xuanjian.run.t),t);
await page.locator('[data-gift-confirm]').click();await page.waitForFunction(()=>xuanjian.run.gift==='whale'&&xuanjian.run.state==='running');await page.locator('#pause').click();await page.waitForSelector('#resume');await page.screenshot({path:`../gift-browser/pause-${w}.png`});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.equal(errors.length,0,errors.join('\n'));results.push({viewport:[w,h],errors,choiceConfirmed:true});await page.close();}
await browser.close();fs.writeFileSync('../gift-browser/result.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));})();
