'use strict';
const assert=require('node:assert/strict');const {Run,SKILLS,RECIPE,Pool}=require('../scripts/content.js');let results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
function quiet(r){r.spawnTimer=1e8;r.eliteAt=r.bossAt=r.eventAt=1e8;return r;}
function enemy(r,type=0,x=r.p.x+70,y=r.p.y){const e=r.spawn(type,false,x,y);e.born=0;return e;}
const step=(r,n=60,input={})=>{for(let i=0;i<n;i++)r.step(1/60,input);};
test('移动归一化、边界、原样例速度',()=>{let a=quiet(new Run(1)),b=quiet(new Run(1));step(a,60,{x:1});step(b,60,{x:1,y:1});assert(Math.abs(Math.hypot(b.p.x-1600,b.p.y-1100)-(a.p.x-1600))<.001);assert(Math.abs(a.p.x-1780)<.001);a.p.x=3134;step(a,60,{x:1});assert.equal(a.p.x,3135);});
test('普通攻击零法力仍造成伤害',()=>{let r=quiet(new Run(1)),e=enemy(r);r.p.mp=0;step(r,50);assert(r.kills>0||e.hp<e.max);assert(r.telemetry.autoShots>0);});
test('经验需要拾取、升级三选一、战斗冻结并恢复',()=>{let r=quiet(new Run(1));r.addDrop(r.p.x,r.p.y,r.need);r.step(.016);assert.equal(r.state,'choice');assert.equal(r.choices.length,3);let t=r.t,x=r.p.x,m=r.p.mp;step(r,60,{x:1,item:true});assert.equal(r.t,t);assert.equal(r.p.x,x);assert.equal(r.p.mp,m);assert(r.choose(0));assert.equal(r.state,'running');r.step(.016,{x:1});assert(r.t>t);});
test('1000 种子候选互异、满级排除、跨道统可选',()=>{let other=false;for(let seed=0;seed<1000;seed++){let r=new Run(seed);r.skills={light:3,gate:1};for(let i=0;i<15;i++){let o=r.offer();assert.equal(new Set(o).size,3);assert(!o.includes('light'));assert(o.every(x=>r.valid().includes(x)));if(o.includes('pure'))other=true;}}assert(other);});
test('同名只升级、三级封顶、无六槽上限',()=>{let r=new Run(2);for(let i=0;i<3;i++){r.openChoice();r.choices[0]='gate';r.choose(0);}assert.equal(r.lv('gate'),3);assert.equal(Object.keys(r.skills).length,1);assert(!r.offer().includes('gate'));for(const s of SKILLS)r.skills[s.id]=1;assert.equal(Object.keys(r.skills).length,SKILLS.length);assert(SKILLS.length>7);});
test('指定五法、异道共存、器物箓气不算神通',()=>{let r=new Run(2);r.skills={gate:1,body:1,edict:1,dusk:1,pure:3,mountain:3};r.gift='whale';r.item='sword';assert(!r.recipe());r.skills.light=1;assert(!r.recipe());r.skills.gate=2;assert(!r.recipe());r.openChoice();r.choices[0]='gate';r.choose(0);assert(r.fruit);assert.equal(r.lv('pure'),3);delete r.skills.light;assert(!r.recipe());});
test('重抽只在成长扣除、不承诺变成缺项',()=>{let r=new Run(3);r.rerolls=2;assert(!r.reroll());r.openChoice();assert(r.reroll());assert.equal(r.rerolls,1);r.openChoice('gift');assert(!r.reroll());assert.equal(r.rerolls,1);});
test('连升队列：每次选择后仍有升级则继续暂停',()=>{let r=quiet(new Run(2));r.xp=100;r.nextChoice();r.choose(0);assert.equal(r.state,'choice');assert.equal(r.level,3);});
test('受箓独立、一次性、重海不回血',()=>{let r=quiet(new Run(3));r.p.hp=40;r.p.mp=0;r.giftPending=true;r.nextChoice();assert.equal(r.choiceKind,'gift');r.choose(0);assert.equal(r.gift,'whale');assert.equal(r.maxMP,160);assert.equal(Object.keys(r.skills).length,0);let hp=r.p.hp,mp=r.p.mp;step(r);assert.equal(r.p.hp,hp);assert(r.p.mp>mp+12.9);r.giftPending=true;r.nextChoice();assert.equal(r.state,'running');});
test('竭命有限代价、冷却、治疗不回寿元',()=>{let r=quiet(new Run(1));r.gift='life';r.p.mp=0;assert(r.lifeUse());assert.equal(r.life,7);assert.equal(r.p.mp,80);assert(!r.lifeUse());r.p.hp=100;assert.equal(r.life,7);for(let i=0;i<7;i++){r.cool.life=0;assert(r.lifeUse());}r.cool.life=0;assert(!r.lifeUse());assert.equal(r.life,0);});
test('器物耗蓝与冷却、法力不足拒绝且不扣负',()=>{let r=quiet(new Run(1)),e=enemy(r);r.p.mp=15;assert(!r.itemUse());assert.equal(r.p.mp,15);r.p.mp=30;assert(r.itemUse());assert.equal(r.p.mp,14);assert(!r.itemUse());assert(e.hp<e.max||!e.active);});
test('青乌锐箭贯穿多个目标',()=>{let r=quiet(new Run(1,'bow'));for(let i=0;i<3;i++)enemy(r,0,1700+i*50,1100);r.cool.attack=100;assert(r.itemUse());step(r,40);assert.equal(r.kills,3);});
test('冲锋先锁方向预警，再突进，可横移规避',()=>{let r=quiet(new Run(1)),e=enemy(r,1,1800,1100);r.cool.attack=100;e.cd=0;r.step(.016);assert.equal(e.phase,'warn');let ax=e.ax;step(r,40,{y:1});assert.equal(e.phase,'warn');assert.equal(e.ax,ax);step(r,60,{y:1});assert(r.telemetry.charges>0);assert.equal(r.p.hp,100);});
test('远射蓄力后发射；射击前移动仍锁原方向',()=>{let r=quiet(new Run(1)),e=enemy(r,2,1920,1100);r.cool.attack=100;e.cd=0;r.step(.016);assert.equal(e.phase,'warn');assert.equal(r.bullets.count,0);step(r,55,{y:1});assert(r.telemetry.enemyShots>0);assert.equal(r.p.hp,100);});
test('地面预警不伤害，激活后伤害与迟缓',()=>{let r=quiet(new Run(1));r.hazard(1600,1100,60,1.2,4);step(r,60);assert.equal(r.p.hp,100);step(r,30);assert(r.p.hp<100);assert(r.p.slow>0);});
test('护持者减伤，优先击杀解除保护',()=>{let r=quiet(new Run(1)),s=enemy(r,4,1800,1100),e=enemy(r,0,1801,1100);r.cool.attack=100;r.step(.016);let h=e.hp;r.hit(e,10);assert(Math.abs(h-e.hp-4)<.001);r.enemies.remove(s);r.step(.016);h=e.hp;r.hit(e,10);assert(Math.abs(h-e.hp-10)<.001);});
test('重甲蓄力后落锤，可走出范围',()=>{let r=quiet(new Run(1)),e=enemy(r,5,1700,1100);r.cool.attack=100;e.cd=0;r.step(.016);assert.equal(e.phase,'warn');step(r,90,{y:1});assert.equal(r.p.hp,100);});
test('首领奖励后继续，无 180 秒结束',()=>{let r=quiet(new Run(1));r.t=181;let e=enemy(r,6);r.hit(e,100000);assert.equal(r.bosses,1);assert.equal(r.rerolls,2);assert.equal(r.state,'running');r.gift='whale';for(let i=0;i<120;i++){if(r.state==='choice')r.choose(0);r.step(1/60);}assert(r.t>182);assert.notEqual(r.state,'ended');});
test('暂停不走时、不恢复资源，结束快照和重开清空',()=>{let r=quiet(new Run(1));r.skills.gate=2;r.p.mp=4;r.pause();step(r,120);assert.equal(r.t,0);assert.equal(r.p.mp,4);r.pause();r.end();let rr=new Run(r.seed,r.item);assert.equal(r.result.skills.gate,2);assert.equal(Object.keys(rr.skills).length,0);assert.equal(rr.t,0);assert.equal(rr.gift,null);assert.equal(rr.rerolls,0);});
test('伤害导致死亡，不继续拾取升级',()=>{let r=quiet(new Run(1));r.p.hp=1;r.hurt(10);assert.equal(r.state,'ended');assert.equal(r.result.reason,'身死道消');let t=r.t;step(r);assert.equal(r.t,t);});
test('池容量和复用、经验总量合并守恒',()=>{let p=new Pool(2),a=p.add({n:1}),b=p.add({n:2});assert.equal(p.add({n:3}),null);p.remove(a);let d=p.add({n:4});assert.equal(d,a);assert.equal(p.count,2);let r=new Run(3);for(let i=0;i<400;i++)r.addDrop(i%20*140,Math.floor(i/20)*100,2);assert(r.drops.count<=110);assert.equal(r.drops.list().reduce((n,d)=>n+d.value,0),800);assert(r.telemetry.dropMerged>0);});
test('神通满级后仍给三种有效奖励',()=>{let r=new Run(1);for(const s of SKILLS)r.skills[s.id]=3;r.vigor=10;r.extraPower=12;r.precision=8;r.training=Object.fromEntries(require('../scripts/engine.js').TRAINING.map(d=>[d.id,d.max]));r.p.hp=r.maxHP;assert.equal(r.offer().length,3);r.openChoice();r.choices=['heal','mana','ward'];const before=r.p.hp+(r.cool.healBuff||0);r.choose(0);assert(r.p.hp+(r.cool.healBuff||0)>before,'满血时调息仍应提供有效续航');});
test('天下明禁闭并消弹，谒天门联动甲兵',()=>{let r=quiet(new Run(1));r.skills={gate:1,light:1};r.cool.gate=r.cool.light=0;let e=enemy(r,5,1720,1100);r.shoot(1650,1100,1600,1100,10,true);r.updateSkills(.016,e);assert(r.allies.count>0);assert(r.allies.list().every(a=>a.empowered>0));assert.equal(r.bullets.count,0);assert(e.stun>0);});
test('仙无漏净地、东羽山凝滞',()=>{let r=quiet(new Run(1));r.skills={pure:1,mountain:1};r.cool.pure=r.cool.mountain=0;let e=enemy(r,5,1750,1100);r.hazard(1600,1100);r.updateSkills(.016,e);assert(!r.zones.list().some(z=>z.kind==='hazard'));assert(r.p.guard>0);r.updateZones(.016);assert(e.slow>0);});
test('蹈危随合围压力加持，小伤抵御更优且无免伤盾',()=>{let r=quiet(new Run(1));r.skills.body=3;for(let i=0;i<5;i++)enemy(r,0,1680,1090+i*8);r.updateSkills(.016,r.nearest());assert.equal(r.p.pressure,1);assert.equal(r.p.body,0);let hp=r.p.hp;r.hurt(10);const small=hp-r.p.hp;assert(small>0&&small<10);r.p.inv=0;hp=r.p.hp;r.hurt(30);const big=hp-r.p.hp;assert(big/30>small/10);r.enemies.forEach(e=>r.enemies.remove(e));const after=r.p.hp;for(let i=0;i<120;i++)r.updateSkills(1/60,null);assert(r.p.hp>after);});
test('赤断镞挪移有域/法力/冷却约束',()=>{let r=quiet(new Run(1));r.skills.dusk=1;assert(!r.blink());r.zones.add({kind:'dusk',x:1600,y:1100,r:215,life:8,age:0,tick:1,stored:0});r.p.mp=7;assert(!r.blink());r.p.mp=20;assert(r.blink());assert.equal(r.p.mp,12);assert(!r.blink());assert(r.p.x>1600);});
test('果位改变令域和挪移规则而非统一增伤',()=>{let r=quiet(new Run(1));for(let id of RECIPE.ids)r.skills[id]=1;r.skills.gate=3;r.fruit=r.recipe();r.zones.add({kind:'edict',x:1500,y:1100,r:140,life:7,age:0,tick:0});r.updateZones(.1);assert(r.zones.list()[0].x>1500);assert.equal(r.power,1);});
console.log(JSON.stringify({suite:'logic + constructed simulation scenarios',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
