'use strict';
const assert=require('node:assert/strict'),X=require('../scripts/field-event.js');
const results=[];function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
function run(){const r=new X.Run(42,'bow','standard');r.spawnTimer=r.eliteAt=r.bossAt=1e8;r.autoItem=false;r.cool.attack=1e8;return r;}
function kill(r,extra={}){const e=r.spawn(0,false,r.p.x+100,r.p.y);Object.assign(e,{born:0},extra);r.hit(e,100000);return e;}
test('ordinary kill pity drops at death position without altering XP or battle RNG',()=>{const a=run(),b=run();a.t=b.t=45;for(let i=0;i<40;i++){kill(a);const e=b.spawn(0,false,b.p.x+100,b.p.y);b.enemies.remove(e);}assert.equal(a.medicineBags.length,1);assert.equal(a.medicineBags[0].x,a.p.x+100);assert.equal(a.kills,40);assert.equal(a.drops.list().reduce((n,d)=>n+d.value,0),80);assert.equal(a.random(),b.random());});
test('cooldown prevents mass kills from creating unlimited healing',()=>{const r=run();r.t=45;for(let i=0;i<200;i++)kill(r);assert.equal(r.medicineBags.length,1);r.t=89.9;kill(r);assert.equal(r.medicineBags.length,1);r.t=90;kill(r);assert.equal(r.medicineBags.length,2);});
test('low-health pity guarantees supply within eight kills after cooldown',()=>{const r=run();r.p.hp=30;r.t=45;for(let i=0;i<8;i++)kill(r);assert.equal(r.medicineBags.length,1);});
test('summoned enemies, double hit and removed enemies cannot farm supply',()=>{const r=run();r.t=45;r.p.hp=30;for(let i=0;i<20;i++)kill(r,{summoned:true});assert.equal(r.medicineBags?.length||0,0);const e=kill(r);r.hit(e,10000);assert.equal(r.medicineProgress.kills,1);const f=r.spawn(0);r.enemies.remove(f);r.hit(f,10000);assert.equal(r.medicineProgress.kills,1);});
test('pickup requires proximity, heals only missing HP, leaves XP untouched',()=>{const r=run();r.p.hp=92;r.medicineBags=[{x:r.p.x+100,y:r.p.y,heal:15}];r.step(.05);assert.equal(r.p.hp,92);r.p.x+=100;r.step(.05);assert.equal(r.p.hp,100);assert.equal(r.telemetry.medicineHealing,8);assert.equal(r.medicineBags.length,0);assert.equal(r.xp,0);});
test('full HP does not consume or magnetize supplies; pause/choice/end freeze pickup',()=>{const r=run();r.medicineBags=[{x:r.p.x,y:r.p.y,heal:15}];r.step(.05);assert.equal(r.medicineBags.length,1);r.p.hp=50;for(const state of ['paused','choice','ended']){r.state=state;r.step(.05);assert.equal(r.p.hp,50);assert.equal(r.medicineBags.length,1);}});
test('only enough bags to fill health are consumed; ground cap keeps old bags',()=>{const r=run();r.p.hp=99;r.medicineBags=Array.from({length:3},()=>({x:r.p.x,y:r.p.y,heal:15}));r.step(.05);assert.equal(r.medicineBags.length,2);r.p.hp=100;r.t=45;for(let i=0;i<50;i++)kill(r);assert.equal(r.medicineBags.length,3);r.t=200;for(let i=0;i<50;i++)kill(r);assert.equal(r.medicineBags.length,3);});
test('drops persist until picked; new runs reset them and result is a snapshot',()=>{const r=run();r.medicineBags=[{x:r.p.x,y:r.p.y,heal:15}];r.p.hp=50;r.step(.05);r.end('主动结束');assert.equal(r.result.medicine.healed,15);r.telemetry.medicineHealing=99;assert.equal(r.result.medicine.healed,15);assert.equal(run().medicineBags?.length||0,0);});
console.log(JSON.stringify({suite:'medicine',passed:results.filter(x=>x.pass).length,total:results.length,results},null,2));process.exitCode=results.every(x=>x.pass)?0:1;
