// Browser emulation; constructed scenarios are not real-device or natural-play evidence.
require('node:fs').mkdirSync('work/mobile',{recursive:true});
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true});const results=[];for(const [w,h,touch] of [[320,568,true],[390,844,true],[844,390,true],[768,1024,true],[1024,768,false],[1440,900,false]]){const page=await browser.newPage({viewport:{width:w,height:h},isMobile:touch,hasTouch:touch});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${process.env.XJ_URL||'http://127.0.0.1:18743/'}?test`);await page.locator('[data-item="sword"]').click();await page.locator('[data-choice="0"]').click();await page.waitForFunction(()=>window.xuanjian.run.state==='running');await page.waitForTimeout(250);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'horizontal page overflow');
const box=await page.locator('#dashAction').boundingBox();await page.evaluate(()=>window.savedDash=document.getElementById('dashAction'));const cdp=touch?await page.context().newCDPSession(page):null;if(cdp)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});else{await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();}await page.waitForTimeout(350);assert(await page.evaluate(()=>savedDash===document.getElementById('dashAction')),'button replaced while pressed');if(cdp){await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else await page.mouse.up();assert(await page.evaluate(()=>xuanjian.run.cool.dash>0),'held click lost');
await page.locator('#pause').click();assert.equal(await page.evaluate(()=>xuanjian.run.state),'paused');const t=await page.evaluate(()=>xuanjian.run.t);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>xuanjian.run.t),t);await page.locator('#pauseAuto').click();await page.locator('#resume').click();await page.waitForTimeout(150);assert(await page.locator('#itemAction').isVisible(),'manual item control missing');
const bounds=await page.evaluate(()=>({compact:XJMobile.matches,footer:document.querySelector('footer').getBoundingClientRect().height,header:document.querySelector('header').getBoundingClientRect().toJSON(),nav:document.getElementById('topRight').getBoundingClientRect().toJSON()}));if(bounds.compact){assert(bounds.header.right<=bounds.nav.left,'header overlaps nav');assert(bounds.footer<100,'footer too tall');}
await page.screenshot({path:`work/mobile/verified-${w}x${h}.png`});assert.equal(errors.length,0,errors.join('\n'));results.push({viewport:[w,h],...bounds,errors});await page.close();}await browser.close();fs.writeFileSync('work/mobile/verification.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));})();
