'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const X=require(fs.existsSync(require('node:path').join(__dirname,'../scripts/field-event.js'))?'../scripts/field-event.js':'../scripts/content.js');
const {Run,RECIPES}=X,results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
function quiet(item='sword'){const r=new Run(42,item,'standard');r.spawnTimer=r.eliteAt=r.bossAt=r.eventAt=1e8;r.autoItem=false;r.cool.attack=1e8;return r;}
function enemy(r,type=0,x=r.p.x+100,y=r.p.y){const e=r.spawn(type,false,x,y);e.born=0;e.hp=e.max=10000;e.speed=0;e.cd=1e8;return e;}
test('持屏候选排除镂金石，仍保留洞泉声果位入口',()=>{const r=quiet('screen');assert(!r.valid().includes('gold'));assert(r.valid().includes('spring'));for(let i=0;i<100;i++)assert(!r.offer().includes('gold'));r.skills=Object.fromEntries(RECIPES[1].ids.filter(id=>id!=='spring').map(id=>[id,1]));r.openChoice();r.choices=['spring'];assert(r.choose(0));assert(!r.fruits.lushui);r.skills.rain=2;r.openChoice();r.choices=['rain'];assert(r.choose(0));assert(r.fruits.lushui);});
test('持屏满级池耗尽后仍有三个有效续航选项',()=>{const r=quiet('screen');r.skills=Object.fromEntries(X.SKILLS.filter(s=>s.id!=='gold').map(s=>[s.id,3]));r.level=60;r.vigor=10;r.extraPower=12;r.precision=8;r.training=Object.fromEntries(X.TRAINING.map(d=>[d.id,d.max]));assert.deepEqual(r.offer().sort(),['heal','mana','ward']);});
test('持屏洞泉声不空耗法力，其他器物照常获得助击',()=>{for(const item of ['screen','bow']){const r=quiet(item),e=enemy(r);r.skills={spring:1};r.updateSkills(.01,e);assert.equal(r.p.mp,item==='screen'?100:78);assert.equal(r.skillCasts?.spring||0,item==='screen'?0:1);}});
test('适配提示说明持屏限制和谷风引火前提，不改构筑',()=>{const r=quiet('screen');assert.match(r.choiceFit('spring').text,/果位/);assert.match(r.choiceFit('edict').text,/普攻/);assert.match(r.choiceFit('firegift',true).text,/雉离行/);r.skills.flame=1;assert.equal(r.choiceFit('firegift',true).tone,'good');assert.equal(r.gift,null);});
test('主修只接受已学有效主动神通，并与手动互斥',()=>{const r=quiet();r.skills={flame:1,gate:1,gold:1};assert(!r.setPrimary('rain'));assert(!r.setPrimary('gold'));assert(r.setPrimary('gate'));assert(r.setManual('gate'));assert.equal(r.primarySkill,null);assert(!r.setPrimary('gate'));assert(r.setManual(null));assert(r.setPrimary('gate'));r.pause();assert(r.setPrimary('flame'));r.state='choice';assert(r.setPrimary(null));});
test('主修优先于满级久候神通，紧急防御仍可插队',()=>{const r=quiet(),e=enemy(r);r.skills={gate:1,fragrance:3,armor:1};r.cool.gate=0;r.t=40;r.skillWait={fragrance:0};r.setPrimary('gate');assert.equal(r.skillOrder(e)[0],'gate');r.p.hp=20;assert.equal(r.skillOrder(e)[0],'armor');});
test('主修缺蓝时蓄法，够蓝后实际施放；冷却中不囤蓝',()=>{const r=quiet(),e=enemy(r);r.skills={gate:1,flame:1};r.cool.gate=0;r.setPrimary('gate');r.p.mp=20;r.updateSkills(.01,e);assert.equal(r.p.mp,20);assert.equal(r.skillBudget,'gate');r.p.mp=26;r.updateSkills(.01,e);assert.equal(r.skillCasts.gate,1);r.p.mp=18;r.updateSkills(.01,e);assert.equal(r.skillCasts.flame,1);});
test('主修无目标时不阻塞其他技能；手动施法不抹掉自动蓄法',()=>{const r=quiet(),e=enemy(r,0,r.p.x+300);r.skills={flame:1,gate:1,armor:1};r.cool.gate=0;r.setPrimary('flame');assert(!r.skillOrder(e).includes('flame'));r.setManual('armor');r.skillBudget='gate';r.castManual();assert.equal(r.skillBudget,'gate');});
test('地图事件按自然时钟出现，暂停和选卡冻结倒计时',()=>{const r=quiet();for(let i=0;i<1801;i++)r.step(.05);assert.equal(r.fieldEvent.status,'available');const t=r.t,deadline=r.fieldEvent.deadline;r.pause();r.step(.05);assert.equal(r.t,t);assert.equal(r.fieldEvent.deadline,deadline);r.state='choice';r.step(.05);assert.equal(r.t,t);});
test('同种子同位置事件一致，未触发事件不消耗刷怪随机序列',()=>{const a=quiet(),b=quiet();a.t=b.t=90;a.updateFieldEvent();assert.equal(a.random(),b.random());b.updateFieldEvent();assert.equal(a.fieldEvent.site,b.fieldEvent.site);});
test('接近才出守卫；实体池不足不会生成半组守卫',()=>{const r=quiet();r.t=90;r.updateFieldEvent();assert.equal(r.enemies.count,0);r.p.x=r.fieldEvent.x;r.p.y=r.fieldEvent.y;for(let i=0;i<158;i++)enemy(r);r.updateFieldEvent();assert.equal(r.enemies.count,158);assert.equal(r.fieldEvent.status,'available');r.enemies.forEach(e=>r.enemies.remove(e));r.updateFieldEvent();assert.equal(r.enemies.count,3);assert.equal(r.fieldEvent.status,'active');assert(r.enemies.list().every(e=>e.fieldGuard&&e.born>0));});
test('真实击杀三名守卫只奖励一次重抽，不以对象消失冒充击杀',()=>{const r=quiet();r.t=90;r.updateFieldEvent();r.p.x=r.fieldEvent.x;r.p.y=r.fieldEvent.y;r.updateFieldEvent();const guards=r.enemies.list();r.enemies.remove(guards[0]);r.updateFieldEvent();assert.equal(r.fieldEvent.kills,0);assert.equal(r.rerolls,0);for(const e of guards.slice(1)){e.born=0;r.hit(e,1e6);}assert.equal(r.rerolls,0);const a=quiet();a.t=90;a.updateFieldEvent();a.p.x=a.fieldEvent.x;a.p.y=a.fieldEvent.y;a.updateFieldEvent();for(const e of a.enemies.list()){e.born=0;a.hit(e,1e6);a.hit(e,1e6);}assert.equal(a.fieldEvent.status,'completed');assert.equal(a.rerolls,1);a.updateFieldEvent();assert.equal(a.rerolls,1);});
test('到期或主动放弃不扣资源、不发奖励，已惊动守卫继续留场',()=>{for(const abandon of [true,false]){const r=quiet();r.t=90;r.updateFieldEvent();r.p.x=r.fieldEvent.x;r.p.y=r.fieldEvent.y;r.updateFieldEvent();r.rerolls=2;if(abandon)assert(r.abandonFieldEvent());else{r.t=r.fieldEvent.deadline;r.updateFieldEvent();}for(const e of r.enemies.list()){e.born=0;r.hit(e,1e6);}assert.equal(r.rerolls,2);assert.equal(r.fieldEvent.status,abandon?'abandoned':'expired');}});
test('事件到期边界的击杀不发迟到奖励，终阵之后不补事件',()=>{const r=quiet();r.t=90;r.updateFieldEvent();r.p.x=r.fieldEvent.x;r.p.y=r.fieldEvent.y;r.updateFieldEvent();r.t=r.fieldEvent.deadline;for(const e of r.enemies.list()){e.born=0;r.hit(e,1e6);}assert.equal(r.rerolls,0);const a=quiet();a.t=720;a.finalStarted=true;a.updateFieldEvent();assert(!a.fieldEvent);});
test('结算保存主修与事件，重开清空；继续无尽不重复事件',()=>{const r=quiet();r.skills.gate=1;r.setPrimary('gate');r.t=90;r.updateFieldEvent();r.abandonFieldEvent();r.end('破阵功成');assert.equal(r.result.primarySkill,'gate');assert.equal(r.result.fieldEvent.status,'abandoned');assert.equal(r.result.version,'0.23.0');r.continueEndless();assert.equal(r.primarySkill,'gate');r.updateFieldEvent();assert.equal(r.fieldEvent.status,'abandoned');const a=quiet();assert(!a.primarySkill);assert(!a.fieldEvent);});
console.log(JSON.stringify({suite:'0.14 playability: unit and constructed regression',passed:results.filter(x=>x.pass).length,total:results.length,results},null,2));process.exitCode=results.every(x=>x.pass)?0:1;
