'use strict';
const assert=require('node:assert/strict');const {Run,SKILLS}=require('../scripts/content.js');
let results=[];function test(name,f){try{f();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
function quiet(mode='endless'){let r=new Run(42,'sword',mode);r.spawnTimer=r.eliteAt=r.bossAt=r.eventAt=1e8;r.autoItem=false;r.cool.attack=1e8;return r;}
function enemy(r){let e=r.spawn(0,false,r.p.x+100,r.p.y);e.born=0;e.hp=e.max=10000;return e;}
test('手动神通不自动释放，F只施放指定神通并扣法力与冷却',()=>{let r=quiet(),e=enemy(r);r.skills={angler:1,peril:1};r.cool.angler=0;r.cool.peril=50;assert(r.setManual('angler'));r.updateSkills(.01,e);assert.equal(r.zones.count,0);assert(r.castManual());assert.equal(r.zones.list()[0].kind,'angler');assert.equal(r.p.mp,74);assert.equal(r.cool.angler,10);assert(!r.castManual());assert.equal(r.p.mp,74);});
test('无敌情/缺法力/暂停不能手动，被动神通不能指定',()=>{let r=quiet();r.skills={angler:1,body:1};assert(!r.setManual('body'));assert(!r.setManual('peril'));r.setManual('angler');assert(!r.castManual());enemy(r);r.p.mp=25;assert(!r.castManual());r.p.mp=100;r.pause();assert(!r.castManual());assert.equal(r.p.mp,100);assert(r.setManual(null));});
test('手动收束与幻饵联动，自动神通继续运行',()=>{let r=quiet(),e=enemy(r);r.skills={angler:1,peril:1};r.cool.angler=0;r.cool.peril=0;r.setManual('peril');r.updateSkills(.01,e);const bait=r.zones.list().find(z=>z.kind==='angler');assert(bait);assert(!r.zones.list().some(z=>z.kind==='peril'));assert(r.castManual());const zone=r.zones.list().find(z=>z.kind==='peril');assert.equal(zone.x,bait.x);assert.equal(zone.y,bait.y);});
test('标准局720秒终阵，暂停冻结，不增普通敌群',()=>{let r=quiet('standard');r.t=719.98;r.pause();r.step(.05);assert(!r.finalStarted);r.pause();r.step(.05);assert(r.finalStarted);const boss=r.enemies.list().find(e=>e.final);assert(boss);const n=r.enemies.count;r.spawnPack();assert.equal(r.enemies.count,n);});
test('存活首领转为终阵，不重复生成',()=>{let r=quiet('standard');const boss=r.spawn(6);r.t=720;r.step(.01);assert(boss.final);assert.equal(r.enemies.list().filter(e=>e.boss).length,1);});
test('终阵击败胜利、停止受伤、保留修为继续无尽及重开清空',()=>{let r=quiet('standard');r.skills={gold:2};r.t=720;r.step(.01);let boss=r.enemies.list().find(e=>e.final);boss.born=0;r.hit(boss,1e9);assert(r.victoryPending);let hp=r.p.hp;r.hurt(9999);assert.equal(r.p.hp,hp);r.step(.01);assert.equal(r.state,'ended');assert.equal(r.result.reason,'破阵功成');assert.equal(r.result.bosses,1);assert(r.continueEndless());assert.equal(r.mode,'endless');assert.equal(r.lv('gold'),2);assert.equal(r.state,'choice');assert.equal(r.choiceKind,'gift');assert(!r.continueEndless());let fresh=new Run(r.seed,r.item,'standard');assert.equal(fresh.lv('gold'),0);assert.equal(fresh.manualSkill,null);});
test('原有无尽局720秒后不转终阵，普通首领不结算',()=>{let r=quiet();r.t=720;r.step(.01);assert(!r.finalStarted);let boss=r.spawn(6);boss.born=0;r.hit(boss,1e9);r.step(.01);assert.equal(r.state,'choice');assert.equal(r.choiceKind,'gift');assert(!r.result);});
test('S/A/B评级保持完整',()=>assert(SKILLS.every(s=>['S','A','B'].includes(s.grade))));
console.log(JSON.stringify({suite:'0.8 refinement',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));process.exitCode=results.every(r=>r.pass)?0:1;
