'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const X=require('../scripts/field-event.js'),UI=require('../scripts/experience-ui.js'),results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
function run(item='bow'){const r=new X.Run(42,item,'standard');r.level=2;r.autoItem=false;r.spawnTimer=r.eliteAt=r.bossAt=1e8;return r;}
function train(r,id){r.openChoice();r.choices=[id];assert(r.choose(0));}
function enemy(r,x=200,y=0){const e=r.spawn(0,false,r.p.x+x,r.p.y+y);e.born=0;e.hp=e.max=10000;e.speed=0;return e;}
function near(a,b){assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);}
function ticks(r,n,input={}){for(let i=0;i<n*20;i++)r.step(.05,input);}
test('5000 seed/weapon ordinary upgrades preserve two skills, one usable training; events preserve skills',()=>{const seen=new Set();for(const item of X.ITEMS)for(let seed=0;seed<1000;seed++){const r=new X.Run(seed,item.id);r.level=2;r.skills.gate=1;r.offerMisses={mingyang:3};r.openChoice();assert.equal(new Set(r.choices).size,3);assert.equal(r.choices.filter(id=>X.SKILLS.some(s=>s.id===id)).length,2);const id=r.choices.find(id=>!X.SKILLS.some(s=>s.id===id));seen.add(id);assert(UI.trainingInfo(r,id));assert(r.choices.some(id=>['body','light','edict','dusk'].includes(id)));if(item.id==='screen')assert(!['haste','weapon'].includes(id));r.rerolls=1;assert(r.reroll());assert.equal(new Set(r.choices).size,3);assert.equal(r.choices.filter(id=>X.SKILLS.some(s=>s.id===id)).length,2);r.openChoice('event');assert(r.choices.every(id=>X.SKILLS.some(s=>s.id===id)));}assert.equal(seen.size,8);});
test('every training ranks through choose, leaves pool at cap, never creates a skill or fruit',()=>{for(const item of X.ITEMS){const r=run(item.id);for(const d of X.TRAINING){if(!r.valid().includes(d.id))continue;for(let n=1;n<=d.max;n++){train(r,d.id);assert.equal(r.trainingLv(d.id),n);assert.equal(r.log.at(-1).level,n);}assert(!r.valid().includes(d.id));r.openChoice();r.choices=[d.id];assert(!r.choose(0));r.state='running';}assert.deepEqual(r.skills,{});assert.deepEqual(r.fruits,{});}});
test('bow arrows actually hit separately at 40%, pierce/guard carry over and spring spends once',()=>{const r=run();train(r,'weapon');train(r,'weapon');r.skills={gold:1,spring:1,edict:1};r.cool.springPower=3;r.springCharges=3;const main=enemy(r,200,0),left=enemy(r,200,-28),right=enemy(r,200,28);main.mark=1;r.autoAttack(main);assert.equal(r.bullets.count,3);const shots=r.bullets.list();near(shots[1].damage,shots[0].damage*.4);near(shots[2].damage,shots[0].damage*.4);assert(shots.every(b=>b.pierce===2&&b.breakGuard));assert.equal(r.springCharges,2);near(10000-main.hp,16);for(let i=0;i<7;i++)r.updateBullets(.05);assert(main.hp<9984&&left.hp<10000&&right.hp<10000);});
test('sword existing sweep reaches wider area with matching effect radius',()=>{const a=run('sword'),b=run('sword');train(b,'weapon');train(b,'weapon');const ae=enemy(a,140),be=enemy(b,140);a.autoAttack(ae);b.autoAttack(be);near(ae.hp,10000);near(be.hp,9989);assert(b.fx.list().some(f=>f.kind==='sword'&&f.r===150));});
test('spear hits four aligned enemies while default hits two; no range/damage inflation',()=>{const a=run('spear'),b=run('spear');train(b,'weapon');train(b,'weapon');const aa=[60,110,160,210].map(x=>enemy(a,x)),bb=[60,110,160,210].map(x=>enemy(b,x));a.autoAttack(aa[0]);b.autoAttack(bb[0]);assert.equal(aa.filter(e=>e.hp<10000).length,2);assert.equal(bb.filter(e=>e.hp<10000).length,4);bb.forEach(e=>near(10000-e.hp,26));});
test('thunderseal acquires a distant target through normal step, unchanged single damage',()=>{const a=run('thunderseal'),b=run('thunderseal');train(b,'weapon');train(b,'weapon');const aa=enemy(a,480),bb=enemy(b,480);a.cool.attack=b.cool.attack=0;a.step(.05);b.step(.05);assert.equal(a.telemetry.autoShots,0);assert.equal(b.telemetry.autoShots,1);near(aa.hp,10000);near(bb.hp,9982);});
test('haste speeds actual auto-fire but leaves item/skill cooldown alone',()=>{for(const item of ['bow','sword','spear','thunderseal']){const a=run(item),b=run(item);for(let i=0;i<3;i++)train(b,'haste');a.cool.item=b.cool.item=5;const aa=enemy(a,100),bb=enemy(b,100);a.autoAttack(aa);b.autoAttack(bb);near(a.cool.attack/b.cool.attack,1.24);assert.equal(b.cool.item,5);ticks(a,10);ticks(b,10);assert(b.telemetry.autoShots>a.telemetry.autoShots);}});
test('movement and mana regeneration apply to real step with low caps and stacking',()=>{const a=run(),b=run();a.cool.attack=b.cool.attack=1e8;for(let i=0;i<3;i++){train(b,'stride');train(b,'manaRegen');}a.p.mp=b.p.mp=0;const x=a.p.x;ticks(a,1,{x:1,y:0});ticks(b,1,{x:1,y:0});near((b.p.x-x)/(a.p.x-x),1.12);near(b.p.mp-a.p.mp,1.8);b.gift='whale';near(b.regen,15.1);});
test('recovery restores only actual HP in running time; no life, revival, pause, or overheal',()=>{const r=run();for(let i=0;i<3;i++)train(r,'recovery');r.p.hp=50;r.p.mp=0;r.life=3;r.cool.attack=1e8;const h=r.healed;ticks(r,10);near(r.p.hp,57.5);near(r.healed-h,7.5);assert.equal(r.life,3);r.pause();ticks(r,2);near(r.p.hp,57.5);r.pause();r.p.hp=r.maxHP-.01;ticks(r,1);near(r.p.hp,r.maxHP);r.p.hp=0;ticks(r,.05);near(r.p.hp,0);r.end();ticks(r,1);near(r.p.hp,0);});
test('growth does not consume or increase stored body/dusk wounds',()=>{const r=run();train(r,'recovery');r.skills={body:1,dusk:1};r.p.battleWounds=20;r.p.hp=50;const z=r.zones.add({kind:'dusk',x:r.p.x,y:r.p.y,r:200,life:6,age:0,playerWound:8,wounds:new Map(),tick:10});r.cool.attack=1e8;r.p.pressure=1;r.p.escape=0;enemy(r,70);enemy(r,-70);const before=r.p.battleWounds;r.step(.05);assert.equal(z.playerWound,8);assert.equal(r.life,8);assert.equal(r.p.battleWounds,before);near(r.p.hp,50.0125);r.p.x+=300;r.step(.05);near(r.p.hp,58.025);assert.equal(z.playerWound,0);r.step(.05);near(r.p.hp,58.0375);});
test('snapshots, standard-to-endless, restart and legacy archive remain separate',()=>{const r=run();train(r,'weapon');train(r,'recovery');train(r,'vigor');r.end('破阵功成');const snap=r.result;assert.equal(snap.training.weapon,1);assert(r.continueEndless());train(r,'weapon');assert.equal(snap.training.weapon,1);assert.equal(r.trainingLv('weapon'),2);assert.deepEqual(new X.Run().trainingSnapshot(),{});let stored;const w={XJ:X};vm.runInNewContext(fs.readFileSync(require.resolve('../scripts/archive.js'),'utf8'),{window:w,localStorage:{getItem:()=>null,setItem:(k,v)=>stored=v},Date,Math,Set,Map,WeakMap});w.XJArchive.merge({schema:1,records:[{id:'old',item:'bow',time:1},{id:'bad',item:'screen',training:{weapon:2,haste:3,recovery:3,manaRegen:99,evil:1}}]});assert(!('training' in w.XJArchive.data.records[0]));assert.equal(w.XJArchive.data.records[1].training.recovery,3);assert(!w.XJArchive.data.records[1].training.weapon);r.end();w.XJArchive.record(r);assert(JSON.parse(stored).records.some(x=>x.training?.weapon===2));});
test('cards and book show exact stage, costs, limits and no undefined across weapons',()=>{for(const item of X.ITEMS){const r=run(item.id);for(const id of r.valid().filter(id=>X.TRAINING.some(d=>d.id===id))){const html=UI.card(r,id,0,()=>'',{},{});assert(html.includes('修行强化'));assert(html.includes('不耗法力'));assert(html.includes('0 → 1 阶'));assert(!html.includes('undefined'));train(r,id);assert(UI.growth(r,id,{}));}const book=UI.trainingSummary(r,true);assert(!book.includes('undefined'));assert(book.includes('不是原著神通'));if(item.id==='screen')assert(!book.includes('熟手'));if(item.id==='bow')assert(book.includes('40%'));}});
console.log(JSON.stringify({suite:'0.16 cultivation logic and constructed regression',passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
