/* 季越人《玄鉴仙族》：苗家人、喜事。阶段炼器与数值为局内压缩。 */
(function(root){'use strict';
const X=typeof module!=='undefined'?require('./dao-expansion.js'):root.XJ;
const {Run,dist}=X;
X.ITEMS.push({id:'dasheng',name:'大昇长戟',action:'挥戟 · 明光',cost:24,cd:7,desc:'普攻以长戟横扫前方，200范围、150度、34伤害，间隔0.85秒。G：24法力，240范围重扫62伤害，冷却7秒。明阳成就首道神通后炼成灵胚，G追加效附戟影与揽照白光；渌水保留法器重扫。'});
Run.prototype.dashengCount=function(){return this.item==='dasheng'&&this.dao==='mingyang'?Math.min(5,this.masteredCount()):0;};
Run.prototype.dashengSweep=function(angle,radius,damage,halfAngle=75*Math.PI/180,attack=false){const spring=attack&&this.cool.springPower>0&&(this.springCharges||0)>0;if(spring)this.springCharges--;const bonus=spring?10+this.lv('spring')*8:0;const targets=this.enemies.list().filter(e=>e.born<=0&&dist(e,this.p)<=radius+e.r&&Math.abs(Math.atan2(Math.sin(Math.atan2(e.y-this.p.y,e.x-this.p.x)-angle),Math.cos(Math.atan2(e.y-this.p.y,e.x-this.p.x)-angle)))<=halfAngle);for(const e of targets)this.hit(e,damage+bonus);if(attack){const marked=targets.find(e=>e.active&&e.mark>0);if(marked)this.hit(marked,10+6*this.lv('edict'),true);}return targets.length;};
const auto=Run.prototype.autoAttack;
Run.prototype.autoAttack=function(target){if(this.item!=='dasheng')return auto.call(this,target);const range=200+this.precision*12;if(!target||dist(target,this.p)>range+target.r)return;const a=Math.atan2(target.y-this.p.y,target.x-this.p.x);this.cool.attack=.85/this.attackSpeed;Object.assign(this.p,{cast:.28,weaponAt:this.t,weaponLife:.42,aim:a});this.telemetry.autoShots++;this.attacks++;this.dashengSweep(a,range,34,(75+this.weaponTraining*10)*Math.PI/180,true);this.effect('dashengSweep',this.p.x,this.p.y,range,.42,{angle:a,half:(75+this.weaponTraining*10)*Math.PI/180});};
const use=Run.prototype.itemUse;
Run.prototype.itemUse=function(){if(this.item!=='dasheng')return use.call(this);if(this.state!=='running'||this.cool.item>0)return false;const e=this.nearest(this.p,240);if(!e){this.notice('大昇 · 靠近敌人再挥戟');return false;}if(!this.spend(24)){this.notice('法力不足 · 普通挥戟不耗法力');return false;}const a=Math.atan2(e.y-this.p.y,e.x-this.p.x);this.cool.item=7;this.telemetry.itemUses++;Object.assign(this.p,{cast:.4,weaponAt:this.t,weaponLife:.5,aim:a});this.dashengSweep(a,240,62);this.effect('dashengSweep',this.p.x,this.p.y,240,.5,{angle:a,half:75*Math.PI/180,strong:true});const n=this.dashengCount();if(n){this.dashengSweep(a,265,20);this.effect('dashengEcho',this.p.x,this.p.y,265,.6,{angle:a,half:75*Math.PI/180});this.dashengLights??=[];this.dashengLights=this.dashengLights.filter(l=>l.life>0).slice(-5);for(let i=0;i<n;i++)this.dashengLights.push({life:4,phase:(i-(n-1)/2)*.4,age:0,x:this.p.x,y:this.p.y});this.telemetry.dashengLights=(this.telemetry.dashengLights||0)+n;}return true;};
const autoUse=Run.prototype.autoItemUse;
Run.prototype.autoItemUse=function(){if(this.item!=='dasheng')return autoUse.call(this);if(this.autoItem&&this.cool.item<=0&&this.nearest(this.p,230)&&this.p.mp>=36+(this.skillBudget&&this.reserveSkill(this.skillBudget)?this.skillCost(this.skillBudget):0))this.itemUse();};
const zones=Run.prototype.updateZones;
Run.prototype.updateZones=function(dt){zones.call(this,dt);if(this.state!=='running'||!this.dashengLights)return;for(const l of this.dashengLights){l.life-=dt;l.age+=dt;const a=this.p.aim+l.phase+Math.sin(l.age*3)*.8,r=185; l.x=this.p.x+Math.cos(a)*r;l.y=this.p.y+Math.sin(a)*r;l.angle=a;const e=this.enemies.list().find(e=>e.born<=0&&dist(e,l)<24+e.r);if(e){this.hit(e,24);l.life=0;this.effect('light',e.x,e.y,20,.2);}}this.dashengLights=this.dashengLights.filter(l=>l.life>0);};
if(typeof module!=='undefined')module.exports=X;
})(typeof globalThis!=='undefined'?globalThis:this);
