/* History and debrief: remembered choices, not permanent power. */
(function(root){'use strict';const {ITEMS,RECIPES,SKILLS,GIFTS}=root.XJ;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const markName=id=>({firstElite:'初战告捷 · 首次精英',firstMastery:'一法三重',firstBoss:'首次击破首领',firstWin:'首次破阵'}[id]||(id.startsWith('master:')?(SKILLS.find(s=>s.id===id.slice(7))?.name||'神通')+' · 三重':id.startsWith('fruit:')?('旧版果位 · '+({mingyang:'明阳',lushui:'渌水'}[id.slice(6)]||'历史达成')):((ITEMS.find(i=>i.id===id.slice(4))?.name||'武器')+'破阵')));
function casts(run){const counts=run.skillCasts;if(!counts)return '';const owned=SKILLS.filter(s=>run.skills?.[s.id]&&root.XJ.Rules.costs[s.id]);if(!owned.length)return '';const waiting=SKILLS.find(s=>s.id===run.skillBudget);return `<details class="casting-summary"><summary>神通施放记录${waiting?' · 正为'+waiting.name+'蓄法':''}</summary><p>主动神通共用法力；施放次数不代表伤害或强度，被动神通不计次。</p><div class="build-chips">${owned.map(s=>`<span>${s.name} · ${counts[s.id]||0} 次</span>`).join('')}</div></details>`;}
function history(){const records=root.XJArchive.data.records;return `<section class="run-history"><h3>最近修行</h3>${records.length?records.slice(-6).reverse().map((r,i)=>`<details><summary><span>${ITEMS.find(x=>x.id===r.item).name} · ${r.mode==='standard'?'破阵挑战':'无尽'}</span><span>${time(r.time)} · ${r.kills} 杀 · ${r.reason||(r.won?'曾破阵':'已结算')}</span></summary><p>${r.realm?esc(r.realm)+' · ':'旧版构筑 · '}箓气：${GIFTS.find(x=>x.id===r.gift)?.name||(r.skills?'未受箓':'旧纪录未保存')}${Object.values(r.fruits||{}).some(Boolean)?' · 旧版果位记录：'+Object.entries(r.fruits).filter(([,v])=>v).map(([id])=>({mingyang:'明阳',lushui:'渌水'}[id]||esc(id))).join('、'):''}</p><div class="build-chips">${r.skills?Object.entries(r.skills).map(([id,lv])=>`<span>${SKILLS.find(x=>x.id===id)?.name||esc(id)} · ${r.realm?(lv===3?'神通':'仙基'+lv+'重'):lv+' 级（旧版）'}</span>`).join('')||'<span>尚未修习</span>':'<span>旧版本未记录构筑详情</span>'}</div>${root.XJPlayUI.record(r)}${casts(r)}${loopReview(r)}${r.seed!==undefined?`<p>种子 ${r.seed} · 版本 ${esc(r.version||'未记录')}。重开只沿用武器、模式和种子；重新选卡，版本变化可能影响进程。</p><button data-history-replay="${records.length-1-i}" ${r.item==='screen'?'disabled':''}>${r.item==='screen'?'此器物本版暂未开放':'沿用种子 · 再试此武器'}</button>`:''}</details>`).join(''):'<p>结束第一局后，这里会记下你的搭配。</p>'}</section>`;}
function overview(){const a=root.XJArchive,d=a.data,core=a.markIds.filter(id=>!id.startsWith('master:')&&!id.startsWith('fruit:')),master=a.markIds.filter(id=>id.startsWith('master:'));return `<details class="journal"><summary><span>修行录</span><small>${d.marks.length} 项达成 · 查看构筑与纪录</small></summary><p class="next-goal">择一道统，蕴养仙基，成就同道五法。</p><div class="journal-marks">${core.map(id=>`<span class="${d.marks.includes(id)?'earned':''}">${d.marks.includes(id)?'✓ ':''}${markName(id)}</span>`).join('')}</div><details><summary>三重图鉴 · ${master.filter(id=>d.marks.includes(id)).length} / ${master.length}</summary><div class="journal-marks">${master.map(id=>`<span class="${d.marks.includes(id)?'earned':''}">${d.marks.includes(id)?'✓ ':''}${markName(id)}</span>`).join('')}</div></details><div class="journal-table"><table><thead><tr><th>武器</th><th>挑战最佳击杀</th><th>无尽最长存活</th></tr></thead><tbody>${ITEMS.map(i=>`<tr><td>${i.name}</td><td>${d.best.standard[i.id]?.kills||'—'}</td><td>${d.best.endless[i.id]?.time?time(d.best.endless[i.id].time):'—'}</td></tr>`).join('')}</tbody></table></div>${history()}<div class="journal-tools"><button id="exportJournal">导出修行录</button><button id="importJournal">合并导入</button><input type="file" accept=".json,application/json" id="journalFile" hidden><span id="journalMessage" role="status">${a.message||'记录达成与搭配，不增加角色数值。'}</span></div></details>`;}
function bind(replay){const exp=document.getElementById('exportJournal'),imp=document.getElementById('importJournal'),file=document.getElementById('journalFile'),message=document.getElementById('journalMessage');if(exp)exp.onclick=()=>root.XJArchive.exportFile();if(imp)imp.onclick=()=>file.click();document.querySelectorAll('[data-history-replay]').forEach(b=>b.onclick=()=>{const r=root.XJArchive.data.records[Number(b.dataset.historyReplay)];if(r&&r.seed!==undefined)replay?.(r);});if(file)file.onchange=async()=>{const f=file.files[0];if(!f)return;try{if(f.size>2000000)throw Error('文件过大');root.XJArchive.merge(JSON.parse(await f.text()));const old=file.closest('.journal');old.outerHTML=overview();document.querySelector('.journal').open=true;bind(replay);document.getElementById('journalMessage').textContent=root.XJArchive.message||'修行录已合并，纪录已更新。';const goal=document.querySelector('#panel .title-content > .next-goal');if(goal)goal.textContent=root.XJArchive.nextGoal();}catch(_){message.textContent='无法识别该存档，现有记录未删除。';}file.value='';};}
const advice={charge:'冲锋锁定方向后横移，利用收势重新站位。',projectile:'沿射线侧移，避免沿弹道后退。',ground:'看清地面预警边界，提前离开即将生效的区域。',slam:'重击蓄势时拉开距离，收势时再靠近。',hook:'向链镰窄道两侧移动，避免被牵回敌群。',contact:'不要停留在敌群中央，沿空隙移动并收取经验。'};
function debrief(run){const r=run.result,a=root.XJArchive,receipt=a.record(run),last=r.lastDamage?.at(-1);let copy='';if(r.reason==='身死道消'&&last)copy=`<div class="death-note"><b>最后一击 · ${esc(last.name)}</b><span>${Math.ceil(last.amount)} 点实际伤害 · ${time(last.at)}</span><p>${advice[last.kind]||advice.contact}</p></div>`;return `<section class="debrief">${receipt.marks.length?`<div class="achievement-note">新达成 · ${receipt.marks.map(markName).join(' / ')}</div>`:''}${receipt.bestKills?'<span class="record-note">本武器本模式 · 击杀新纪录</span>':''}${receipt.bestTime&&r.mode==='endless'?'<span class="record-note">无尽存活新纪录</span>':''}${copy}${loopReview(r)}${root.XJPlayUI.record(r)}${casts(r)}<p class="next-goal">择一道统，蕴养仙基，成就同道五法。</p><small>${a.message||'修行录已保存 · 重开时本局能力清空'}</small></section>`;}
function loopReview(r){const d=r.loop;if(!d)return '';const wait=Number.isFinite(d.manaWait)?d.manaWait:0,primary=SKILLS.find(s=>s.id===r.primarySkill)?.name||'均衡调度';const routes='';const advice=wait>r.time*.15?'下一局可先精修主力或补调元，再增加耗法神通；也可换长鲸比较续航。':r.reason==='身死道消'?'下一局先保留主力输出，尝试固本或轻身，把一次强敌后的经验收回来。':'下一局可换普攻联动或聚怪路线，比较不同成长顺序。';return `<section class="loop-review"><b>本局如何成型</b>${r.medicine?`<p>药囊拾取 ${r.medicine.picked} 份 · 实际回复 ${Math.round(r.medicine.healed)} 气血 · 留在山场 ${r.medicine.left} 份</p>`:''}<p>主修 ${primary} · 神通缺法等待约 ${Math.round(wait)} 秒（有可施放目标时累计，不等于全部停火）</p>${routes}<p>${advice}</p></section>`;}
root.XJJournalUI={loopReview,overview,bind,debrief,casts};
})(window);
