/* Preferences are local and optional; combat rules never read them. */
(function(root){'use strict';const KEY='jibichangsheng.preferences.v1';let value={muted:false,volume:1,reduced:false},message='';
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw){value.muted=raw.muted===true;value.reduced=raw.reduced===true;if(typeof raw.volume==='number'&&Number.isFinite(raw.volume))value.volume=Math.max(0,Math.min(1,raw.volume));}}catch(_){message='设置暂不能读取，本次使用默认设置。';}
const gains=new Map();function save(){try{localStorage.setItem(KEY,JSON.stringify(value));message='';}catch(_){message='设置仅在本次打开期间生效。';}for(const [ctx,g] of gains)g.gain.setTargetAtTime(value.muted?0:value.volume,ctx.currentTime,.02);}
function destination(ctx){if(!gains.has(ctx)){const g=ctx.createGain();g.gain.value=value.muted?0:value.volume;g.connect(ctx.destination);gains.set(ctx,g);}return gains.get(ctx);}
function panel(){return `<details class="preferences"><summary>声音与动态效果</summary><label><input id="prefSound" type="checkbox" ${value.muted?'':'checked'}> 开启音效</label><label>音效音量 <input id="prefVolume" type="range" min="0" max="100" value="${Math.round(value.volume*100)}"><output id="prefVolumeText">${Math.round(value.volume*100)}%</output></label><label><input id="prefMotion" type="checkbox" ${value.reduced?'checked':''}> 减少装饰动效</label><small>同时遵循系统的减少动态效果设置；危险预警保持显示。</small><small id="prefMessage" role="status">${message||'设置会在此浏览器中保留。'}</small></details>`;}
function bind(changed){const sound=document.getElementById('prefSound'),volume=document.getElementById('prefVolume'),motion=document.getElementById('prefMotion');const update=()=>{value.muted=!sound.checked;value.volume=Number(volume.value)/100;value.reduced=motion.checked;save();document.getElementById('prefVolumeText').textContent=volume.value+'%';document.getElementById('prefMessage').textContent=message||'设置已保存。';changed?.();};if(sound){sound.onchange=update;volume.oninput=update;motion.onchange=update;}}
root.XJPreferences={panel,bind,destination,setMuted(muted){value.muted=muted;save();const check=document.getElementById('prefSound');if(check)check.checked=!muted;},get muted(){return value.muted;},get reduced(){return value.reduced;}};
})(window);
